
import * as Viewer from '../viewer.js';
import { DataFetcher } from '../DataFetcher.js';
import { GfxDevice, GfxTexture } from '../gfx/platform/GfxPlatform.js';
import { SceneContext } from '../SceneBase.js';
import { FezRenderer, FezArtObjectRenderer } from './FezRenderer.js';
import { TrilesetData } from './TrileData.js';
import { ArtObjectData } from './ArtObjectData.js';
import { BackgroundPlaneData } from './BackgroundPlaneData.js';
import { GfxRenderCache } from '../gfx/render/GfxRenderCache.js';
import { SkyData } from './Sky.js';
import { FezContentTypeReaderManager, Fez_ArtObject, Fez_TrileSet, Fez_AnimatedTexture, Fez_Level } from './XNB_Fez.js';
import { parse, XNA_Texture2D } from './XNB.js';
import { makeTextureFromXNA_Texture2D } from './Texture.js';
import { assertExists } from '../util.js';

const pathBase = 'Fez';

export class ModelCache {
    public promiseCache = new Map<string, Promise<void>>();
    public trilesetDatas: TrilesetData[] = [];
    public artObjectDatas: ArtObjectData[] = [];
    public backgroundPlaneDatas: BackgroundPlaneData[] = [];
    public skyDatas: SkyData[] = [];
    public textureCache = new Map<string, GfxTexture>();
    public renderCache: GfxRenderCache;
    private fezTypeReaderManager = new FezContentTypeReaderManager();

    constructor(device: GfxDevice, private dataFetcher: DataFetcher) {
        this.renderCache = new GfxRenderCache(device);
    }

    public waitForLoad(): Promise<void> {
        return Promise.all(this.promiseCache.values()) as unknown as Promise<void>;
    }

    public async fetchXNB<T>(path: string): Promise<T> {
        const data = await this.dataFetcher.fetchData(`${pathBase}/${path.toLowerCase()}`);
        return parse<T>(this.fezTypeReaderManager, data);
    }

    private async fetchTrilesetInternal(path: string): Promise<void> {
        const device = this.renderCache.device;
        const data = await this.fetchXNB<Fez_TrileSet>(`xnb/trile sets/${path}.xnb`);
        this.trilesetDatas.push(new TrilesetData(device, this.renderCache, path, data));
    }

    private async fetchArtObjectInternal(path: string): Promise<void> {
        const device = this.renderCache.device;
        const xnb = await this.fetchXNB<Fez_ArtObject>(`xnb/art objects/${path}.xnb`);
        this.artObjectDatas.push(new ArtObjectData(device, this.renderCache, path, xnb));
    }

    private async fetchBackgroundPlaneInternal(path: string, isAnimated: boolean): Promise<void> {
        const device = this.renderCache.device;
        if (isAnimated) {
            const data = await this.fetchXNB<Fez_AnimatedTexture>(`xnb/background planes/${path}.xnb`);
            this.backgroundPlaneDatas.push(new BackgroundPlaneData(device, path, data.texture, data));
        } else {
            const data = await this.fetchXNB<XNA_Texture2D>(`xnb/background planes/${path}.xnb`);
            this.backgroundPlaneDatas.push(new BackgroundPlaneData(device, path, data, null));
        }
    }

    private async fetchSkyDataInternal(path: string): Promise<void> {
        this.skyDatas.push(await SkyData.fetch(this, path));
    }

    private async fetchTextureInternal(path: string): Promise<void> {
        const device = this.renderCache.device;
        const tex = await this.fetchXNB<XNA_Texture2D>(path);
        const gfxTexture = makeTextureFromXNA_Texture2D(device, tex);
        this.textureCache.set(path, gfxTexture);
    }

    public requestTrileset(path: string): void {
        const key = `trile sets/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchTrilesetInternal(path));
    }

    public requestArtObject(path: string): void {
        const key = `art objects/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchArtObjectInternal(path));
    }

    public requestBackgroundPlane(path: string, isAnimated: boolean): void {
        const key = `background planes/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchBackgroundPlaneInternal(path, isAnimated));
    }

    public requestSky(path: string): void {
        const key = `skies/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchSkyDataInternal(path));
    }

    public requestTexture(path: string): Promise<void> {
        const key = `textures/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchTextureInternal(path));
        return this.promiseCache.get(key)!;
    }

    public getTexture(path: string): GfxTexture {
        return assertExists(this.textureCache.get(path));
    }

    public destroy(device: GfxDevice): void {
        this.renderCache.destroy();
        for (let i = 0; i < this.trilesetDatas.length; i++)
            this.trilesetDatas[i].destroy(device);
        for (let i = 0; i < this.artObjectDatas.length; i++)
            this.artObjectDatas[i].destroy(device);
        for (let i = 0; i < this.backgroundPlaneDatas.length; i++)
            this.backgroundPlaneDatas[i].destroy(device);
        for (let i = 0; i < this.skyDatas.length; i++)
            this.skyDatas[i].destroy(device);
        for (const texture of this.textureCache.values())
            device.destroyTexture(texture);
    }
}

class FezSceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string) {
    }

    public async createScene(device: GfxDevice, context: SceneContext): Promise<Viewer.SceneGfx> {
        const cache = await context.dataShare.ensureObject<ModelCache>(`${pathBase}/ModelCache`, async () => {
            return new ModelCache(device, context.dataFetcher);
        });

        const level = await cache.fetchXNB<Fez_Level>(`xnb/levels/${this.id}.xnb`);

        cache.requestTrileset(level.trileSetName);
        cache.requestSky(level.skyName);

        for (const artObject of level.artObjects.values())
            cache.requestArtObject(artObject.name);

        for (const backgroundPlane of level.backgroundPlanes.values())
            cache.requestBackgroundPlane(backgroundPlane.textureName, backgroundPlane.animated);

        await cache.waitForLoad();

        return new FezRenderer(device, cache, level);
    }
}

class FezArtObjectSceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string) {
    }

    public async createScene(device: GfxDevice, context: SceneContext): Promise<Viewer.SceneGfx> {
        const cache = await context.dataShare.ensureObject<ModelCache>(`${pathBase}/ModelCache`, async () => {
            return new ModelCache(device, context.dataFetcher);
        });

        const xnb = await cache.fetchXNB<Fez_ArtObject>(`xnb/art objects/${this.id}.xnb`);
        const artObjectData = new ArtObjectData(device, cache.renderCache, this.id, xnb);
        return new FezArtObjectRenderer(device, artObjectData);
    }
}

const id = 'Fez';
const name = 'Fez';
const sceneDescs: (string | Viewer.SceneDesc)[] = [
    'Levels',
    new FezSceneDesc('abandoned_a', 'abandoned_a'),
    new FezSceneDesc('abandoned_b', 'abandoned_b'),
    new FezSceneDesc('abandoned_c', 'abandoned_c'),
    new FezSceneDesc('ancient_walls', 'ancient_walls'),
    new FezSceneDesc('arch', 'arch'),
    new FezSceneDesc('bell_tower', 'bell_tower'),
    new FezSceneDesc('big_owl', 'big_owl'),
    new FezSceneDesc('big_tower', 'big_tower'),
    new FezSceneDesc('boileroom', 'boileroom'),
    new FezSceneDesc('cabin_interior_a', 'cabin_interior_a'),
    new FezSceneDesc('cabin_interior_b', 'cabin_interior_b'),
    new FezSceneDesc('clock', 'clock'),
    new FezSceneDesc('cmy', 'cmy'),
    new FezSceneDesc('cmy_b', 'cmy_b'),
    new FezSceneDesc('cmy_fork', 'cmy_fork'),
    new FezSceneDesc('code_machine', 'code_machine'),
    new FezSceneDesc('crypt', 'crypt'),
    new FezSceneDesc('drum', 'drum'),
    new FezSceneDesc('elders', 'elders'),
    new FezSceneDesc('extractor_a', 'extractor_a'),
    new FezSceneDesc('five_towers', 'five_towers'),
    new FezSceneDesc('five_towers_cave', 'five_towers_cave'),
    new FezSceneDesc('fox', 'fox'),
    new FezSceneDesc('fractal', 'fractal'),
    new FezSceneDesc('geezer_house', 'geezer_house'),
    new FezSceneDesc('geezer_house_2d', 'geezer_house_2d'),
    new FezSceneDesc('globe', 'globe'),
    new FezSceneDesc('globe_int', 'globe_int'),
    new FezSceneDesc('gomez_house', 'gomez_house'),
    new FezSceneDesc('gomez_house_2d', 'gomez_house_2d'),
    new FezSceneDesc('gomez_house_end_32', 'gomez_house_end_32'),
    new FezSceneDesc('gomez_house_end_64', 'gomez_house_end_64'),
    new FezSceneDesc('grave_cabin', 'grave_cabin'),
    new FezSceneDesc('grave_ghost', 'grave_ghost'),
    new FezSceneDesc('grave_lesser_gate', 'grave_lesser_gate'),
    new FezSceneDesc('grave_treasure_a', 'grave_treasure_a'),
    new FezSceneDesc('graveyard_a', 'graveyard_a'),
    new FezSceneDesc('graveyard_gate', 'graveyard_gate'),
    new FezSceneDesc('hex_rebuild', 'hex_rebuild'),
    new FezSceneDesc('indust_abandoned_a', 'indust_abandoned_a'),
    new FezSceneDesc('industrial_city', 'industrial_city'),
    new FezSceneDesc('industrial_hub', 'industrial_hub'),
    new FezSceneDesc('industrial_superspin', 'industrial_superspin'),
    new FezSceneDesc('kitchen', 'kitchen'),
    new FezSceneDesc('kitchen_2d', 'kitchen_2d'),
    new FezSceneDesc('lava', 'lava'),
    new FezSceneDesc('lava_fork', 'lava_fork'),
    new FezSceneDesc('lava_skull', 'lava_skull'),
    new FezSceneDesc('library_interior', 'library_interior'),
    new FezSceneDesc('lighthouse', 'lighthouse'),
    new FezSceneDesc('lighthouse_house_a', 'lighthouse_house_a'),
    new FezSceneDesc('lighthouse_spin', 'lighthouse_spin'),
    new FezSceneDesc('mausoleum', 'mausoleum'),
    new FezSceneDesc('memory_core', 'memory_core'),
    new FezSceneDesc('mine_a', 'mine_a'),
    new FezSceneDesc('mine_bomb_pillar', 'mine_bomb_pillar'),
    new FezSceneDesc('mine_wrap', 'mine_wrap'),
    new FezSceneDesc('nature_hub', 'nature_hub'),
    new FezSceneDesc('nuzu_abandoned_a', 'nuzu_abandoned_a'),
    new FezSceneDesc('nuzu_abandoned_b', 'nuzu_abandoned_b'),
    new FezSceneDesc('nuzu_boilerroom', 'nuzu_boilerroom'),
    new FezSceneDesc('nuzu_dorm', 'nuzu_dorm'),
    new FezSceneDesc('nuzu_school', 'nuzu_school'),
    new FezSceneDesc('observatory', 'observatory'),
    new FezSceneDesc('octoheahedron', 'octoheahedron'),
    new FezSceneDesc('oldschool', 'oldschool'),
    new FezSceneDesc('oldschool_ruins', 'oldschool_ruins'),
    new FezSceneDesc('orrery', 'orrery'),
    new FezSceneDesc('orrery_b', 'orrery_b'),
    new FezSceneDesc('owl', 'owl'),
    new FezSceneDesc('parlor', 'parlor'),
    new FezSceneDesc('parlor_2d', 'parlor_2d'),
    new FezSceneDesc('pivot_one', 'pivot_one'),
    new FezSceneDesc('pivot_two', 'pivot_two'),
    new FezSceneDesc('pivot_three', 'pivot_three'),
    new FezSceneDesc('pivot_three_cave', 'pivot_three_cave'),
    new FezSceneDesc('pivot_watertower', 'pivot_watertower'),
    new FezSceneDesc('purple_lodge', 'purple_lodge'),
    new FezSceneDesc('purple_lodge_ruin', 'purple_lodge_ruin'),
    new FezSceneDesc('pyramid', 'pyramid'),
    new FezSceneDesc('quantum', 'quantum'),
    new FezSceneDesc('rails', 'rails'),
    new FezSceneDesc('ritual', 'ritual'),
    new FezSceneDesc('school', 'school'),
    new FezSceneDesc('school_2d', 'school_2d'),
    new FezSceneDesc('sewer_fork', 'sewer_fork'),
    new FezSceneDesc('sewer_geyser', 'sewer_geyser'),
    new FezSceneDesc('sewer_hub', 'sewer_hub'),
    new FezSceneDesc('sewer_lesser_gate_b', 'sewer_lesser_gate_b'),
    new FezSceneDesc('sewer_pillars', 'sewer_pillars'),
    new FezSceneDesc('sewer_pivot', 'sewer_pivot'),
    new FezSceneDesc('sewer_qr', 'sewer_qr'),
    new FezSceneDesc('sewer_start', 'sewer_start'),
    new FezSceneDesc('sewer_to_lava', 'sewer_to_lava'),
    new FezSceneDesc('sewer_treasure_one', 'sewer_treasure_one'),
    new FezSceneDesc('sewer_treasure_two', 'sewer_treasure_two'),
    new FezSceneDesc('showers', 'showers'),
    new FezSceneDesc('skull', 'skull'),
    new FezSceneDesc('skull_b', 'skull_b'),
    new FezSceneDesc('spinning_plates', 'spinning_plates'),
    new FezSceneDesc('stargate', 'stargate'),
    new FezSceneDesc('stargate_ruins', 'stargate_ruins'),
    new FezSceneDesc('superspin_cave', 'superspin_cave'),
    new FezSceneDesc('telescope', 'telescope'),
    new FezSceneDesc('temple_of_love', 'temple_of_love'),
    new FezSceneDesc('throne', 'throne'),
    new FezSceneDesc('tree', 'tree'),
    new FezSceneDesc('tree_crumble', 'tree_crumble'),
    new FezSceneDesc('tree_of_death', 'tree_of_death'),
    new FezSceneDesc('tree_roots', 'tree_roots'),
    new FezSceneDesc('tree_sky', 'tree_sky'),
    new FezSceneDesc('triple_pivot_cave', 'triple_pivot_cave'),
    new FezSceneDesc('two_walls', 'two_walls'),
    new FezSceneDesc('villageville_2d', 'villageville_2d'),
    new FezSceneDesc('villageville_3d', 'villageville_3d'),
    new FezSceneDesc('villageville_3d_end_32', 'villageville_3d_end_32'),
    new FezSceneDesc('villageville_3d_end_64', 'villageville_3d_end_64'),
    new FezSceneDesc('visitor', 'visitor'),
    new FezSceneDesc('wall_hole', 'wall_hole'),
    new FezSceneDesc('wall_interior_a', 'wall_interior_a'),
    new FezSceneDesc('wall_interior_b', 'wall_interior_b'),
    new FezSceneDesc('wall_interior_hole', 'wall_interior_hole'),
    new FezSceneDesc('wall_kitchen', 'wall_kitchen'),
    new FezSceneDesc('wall_school', 'wall_school'),
    new FezSceneDesc('wall_village', 'wall_village'),
    new FezSceneDesc('water_pyramid', 'water_pyramid'),
    new FezSceneDesc('water_tower', 'water_tower'),
    new FezSceneDesc('water_wheel', 'water_wheel'),
    new FezSceneDesc('water_wheel_b', 'water_wheel_b'),
    new FezSceneDesc('waterfall', 'waterfall'),
    new FezSceneDesc('waterfall_alt', 'waterfall_alt'),
    new FezSceneDesc('watertower_secret', 'watertower_secret'),
    new FezSceneDesc('weightswitch_temple', 'weightswitch_temple'),
    new FezSceneDesc('well_2', 'well_2'),
    new FezSceneDesc('windmill_cave', 'windmill_cave'),
    new FezSceneDesc('windmill_int', 'windmill_int'),
    new FezSceneDesc('zu_4_side', 'zu_4_side'),
    new FezSceneDesc('zu_bridge', 'zu_bridge'),
    new FezSceneDesc('zu_city', 'zu_city'),
    new FezSceneDesc('zu_city_ruins', 'zu_city_ruins'),
    new FezSceneDesc('zu_code_loop', 'zu_code_loop'),
    new FezSceneDesc('zu_fork', 'zu_fork'),
    new FezSceneDesc('zu_heads', 'zu_heads'),
    new FezSceneDesc('zu_house_empty', 'zu_house_empty'),
    new FezSceneDesc('zu_house_empty_b', 'zu_house_empty_b'),
    new FezSceneDesc('zu_house_qr', 'zu_house_qr'),
    new FezSceneDesc('zu_house_ruin_gate', 'zu_house_ruin_gate'),
    new FezSceneDesc('zu_house_ruin_visitors', 'zu_house_ruin_visitors'),
    new FezSceneDesc('zu_house_scaffolding', 'zu_house_scaffolding'),
    new FezSceneDesc('zu_library', 'zu_library'),
    new FezSceneDesc('zu_switch', 'zu_switch'),
    new FezSceneDesc('zu_switch_b', 'zu_switch_b'),
    new FezSceneDesc('zu_tetris', 'zu_tetris'),
    new FezSceneDesc('zu_throne_ruins', 'zu_throne_ruins'),
    new FezSceneDesc('zu_unfold', 'zu_unfold'),
    new FezSceneDesc('zu_zuish', 'zu_zuish'),
    'Art Objects',
    new FezArtObjectSceneDesc('1_bit_doorao', '1_bit_doorao'),
    new FezArtObjectSceneDesc('16_bit_doorao', '16_bit_doorao'),
    new FezArtObjectSceneDesc('2_bit_doorao', '2_bit_doorao'),
    new FezArtObjectSceneDesc('3-bit_doorao', '3-bit_doorao'),
    new FezArtObjectSceneDesc('32_bit_door_brokenao', '32_bit_door_brokenao'),
    new FezArtObjectSceneDesc('32_bit_doorao', '32_bit_doorao'),
    new FezArtObjectSceneDesc('4_bit_doorao', '4_bit_doorao'),
    new FezArtObjectSceneDesc('4_side_blockao', '4_side_blockao'),
    new FezArtObjectSceneDesc('64_bit_doorao', '64_bit_doorao'),
    new FezArtObjectSceneDesc('8bit_doorao', '8bit_doorao'),
    new FezArtObjectSceneDesc('bell_hookao', 'bell_hookao'),
    new FezArtObjectSceneDesc('bellao', 'bellao'),
    new FezArtObjectSceneDesc('big_owl_headao', 'big_owl_headao'),
    new FezArtObjectSceneDesc('big_owl_pyramid_headao', 'big_owl_pyramid_headao'),
    new FezArtObjectSceneDesc('big_owl_pyramidao', 'big_owl_pyramidao'),
    new FezArtObjectSceneDesc('big_owlao', 'big_owlao'),
    new FezArtObjectSceneDesc('big_spinao', 'big_spinao'),
    new FezArtObjectSceneDesc('big_stone_doorao', 'big_stone_doorao'),
    new FezArtObjectSceneDesc('big_telescopeao', 'big_telescopeao'),
    new FezArtObjectSceneDesc('big_tombstone_baseao', 'big_tombstone_baseao'),
    new FezArtObjectSceneDesc('big_tombstoneao', 'big_tombstoneao'),
    new FezArtObjectSceneDesc('big_tree_orangeao', 'big_tree_orangeao'),
    new FezArtObjectSceneDesc('big_tree_pinkao', 'big_tree_pinkao'),
    new FezArtObjectSceneDesc('big_treeao', 'big_treeao'),
    new FezArtObjectSceneDesc('big_water_tankao', 'big_water_tankao'),
    new FezArtObjectSceneDesc('big_windmillao', 'big_windmillao'),
    new FezArtObjectSceneDesc('birdcage_aao', 'birdcage_aao'),
    new FezArtObjectSceneDesc('bookshelf_bigao', 'bookshelf_bigao'),
    new FezArtObjectSceneDesc('bookshelfao', 'bookshelfao'),
    new FezArtObjectSceneDesc('bookthingao', 'bookthingao'),
    new FezArtObjectSceneDesc('bunkbedsao', 'bunkbedsao'),
    new FezArtObjectSceneDesc('cameraao', 'cameraao'),
    new FezArtObjectSceneDesc('candles_aao', 'candles_aao'),
    new FezArtObjectSceneDesc('candles_bao', 'candles_bao'),
    new FezArtObjectSceneDesc('candles_cao', 'candles_cao'),
    new FezArtObjectSceneDesc('clock_baseao', 'clock_baseao'),
    new FezArtObjectSceneDesc('clock_boltao', 'clock_boltao'),
    new FezArtObjectSceneDesc('clock_cubeao', 'clock_cubeao'),
    new FezArtObjectSceneDesc('clock_topao', 'clock_topao'),
    new FezArtObjectSceneDesc('clockcoreao', 'clockcoreao'),
    new FezArtObjectSceneDesc('clockfaceao', 'clockfaceao'),
    new FezArtObjectSceneDesc('clockhand_bao', 'clockhand_bao'),
    new FezArtObjectSceneDesc('clockhand_gao', 'clockhand_gao'),
    new FezArtObjectSceneDesc('clockhand_rao', 'clockhand_rao'),
    new FezArtObjectSceneDesc('clockhand_wao', 'clockhand_wao'),
    new FezArtObjectSceneDesc('cmy_crystal_cao', 'cmy_crystal_cao'),
    new FezArtObjectSceneDesc('cmy_crystal_kao', 'cmy_crystal_kao'),
    new FezArtObjectSceneDesc('cmy_crystal_mao', 'cmy_crystal_mao'),
    new FezArtObjectSceneDesc('cmy_crystal_yao', 'cmy_crystal_yao'),
    new FezArtObjectSceneDesc('cmy_doorao', 'cmy_doorao'),
    new FezArtObjectSceneDesc('cmy_head_aao', 'cmy_head_aao'),
    new FezArtObjectSceneDesc('cmy_head_bao', 'cmy_head_bao'),
    new FezArtObjectSceneDesc('cmy_monolithao', 'cmy_monolithao'),
    new FezArtObjectSceneDesc('cmy_postao', 'cmy_postao'),
    new FezArtObjectSceneDesc('cmy_zuhead_lao', 'cmy_zuhead_lao'),
    new FezArtObjectSceneDesc('cmy_zuhead_sao', 'cmy_zuhead_sao'),
    new FezArtObjectSceneDesc('cmyk_doorao', 'cmyk_doorao'),
    new FezArtObjectSceneDesc('code_machine_aao', 'code_machine_aao'),
    new FezArtObjectSceneDesc('code_monolith_codemachineao', 'code_monolith_codemachineao'),
    new FezArtObjectSceneDesc('code_monolith_waterfallao', 'code_monolith_waterfallao'),
    new FezArtObjectSceneDesc('crossao', 'crossao'),
    new FezArtObjectSceneDesc('crownao', 'crownao'),
    new FezArtObjectSceneDesc('cube_pillarao', 'cube_pillarao'),
    new FezArtObjectSceneDesc('cube_tree_d_pinkao', 'cube_tree_d_pinkao'),
    new FezArtObjectSceneDesc('cube_tree_dao', 'cube_tree_dao'),
    new FezArtObjectSceneDesc('cube_tree_orangeao', 'cube_tree_orangeao'),
    new FezArtObjectSceneDesc('deathskull_aao', 'deathskull_aao'),
    new FezArtObjectSceneDesc('deathskull_bao', 'deathskull_bao'),
    new FezArtObjectSceneDesc('downgrowth_aao', 'downgrowth_aao'),
    new FezArtObjectSceneDesc('downgrowth_bao', 'downgrowth_bao'),
    new FezArtObjectSceneDesc('evol_pillar2222ao', 'evol_pillar2222ao'),
    new FezArtObjectSceneDesc('exit_pillarao', 'exit_pillarao'),
    new FezArtObjectSceneDesc('extractorao', 'extractorao'),
    new FezArtObjectSceneDesc('fake_bender_lao', 'fake_bender_lao'),
    new FezArtObjectSceneDesc('fake_emitter_lao', 'fake_emitter_lao'),
    new FezArtObjectSceneDesc('fake_emitter_tao', 'fake_emitter_tao'),
    new FezArtObjectSceneDesc('fake_timeswitch_movingpartao', 'fake_timeswitch_movingpartao'),
    new FezArtObjectSceneDesc('fake_timeswitchao', 'fake_timeswitchao'),
    new FezArtObjectSceneDesc('fez_signao', 'fez_signao'),
    new FezArtObjectSceneDesc('fifty_signao', 'fifty_signao'),
    new FezArtObjectSceneDesc('food_counter_aao', 'food_counter_aao'),
    new FezArtObjectSceneDesc('food_stuff_0ao', 'food_stuff_0ao'),
    new FezArtObjectSceneDesc('food_stuff_1ao', 'food_stuff_1ao'),
    new FezArtObjectSceneDesc('food_stuff_2ao', 'food_stuff_2ao'),
    new FezArtObjectSceneDesc('food_stuff_3ao', 'food_stuff_3ao'),
    new FezArtObjectSceneDesc('fork_blueao', 'fork_blueao'),
    new FezArtObjectSceneDesc('fork_greenao', 'fork_greenao'),
    new FezArtObjectSceneDesc('fork_redao', 'fork_redao'),
    new FezArtObjectSceneDesc('forkao', 'forkao'),
    new FezArtObjectSceneDesc('fps_post_pao', 'fps_post_pao'),
    new FezArtObjectSceneDesc('fps_post_wao', 'fps_post_wao'),
    new FezArtObjectSceneDesc('fractal_cubeao', 'fractal_cubeao'),
    new FezArtObjectSceneDesc('fractal_globe_baseao', 'fractal_globe_baseao'),
    new FezArtObjectSceneDesc('fractal_globe_topao', 'fractal_globe_topao'),
    new FezArtObjectSceneDesc('fractal_globeao', 'fractal_globeao'),
    new FezArtObjectSceneDesc('gargoyle_aao', 'gargoyle_aao'),
    new FezArtObjectSceneDesc('gate_brokenao', 'gate_brokenao'),
    new FezArtObjectSceneDesc('gate_graveao', 'gate_graveao'),
    new FezArtObjectSceneDesc('gate_industrialao', 'gate_industrialao'),
    new FezArtObjectSceneDesc('gate_sewerao', 'gate_sewerao'),
    new FezArtObjectSceneDesc('gateao', 'gateao'),
    new FezArtObjectSceneDesc('gen_1ao', 'gen_1ao'),
    new FezArtObjectSceneDesc('gen_2ao', 'gen_2ao'),
    new FezArtObjectSceneDesc('gen_3ao', 'gen_3ao'),
    new FezArtObjectSceneDesc('gen_4ao', 'gen_4ao'),
    new FezArtObjectSceneDesc('gen_baseao', 'gen_baseao'),
    new FezArtObjectSceneDesc('gen_capao', 'gen_capao'),
    new FezArtObjectSceneDesc('gen_doorframeao', 'gen_doorframeao'),
    new FezArtObjectSceneDesc('giant_skullao', 'giant_skullao'),
    new FezArtObjectSceneDesc('giant_tree_pinkao', 'giant_tree_pinkao'),
    new FezArtObjectSceneDesc('giant_treeao', 'giant_treeao'),
    new FezArtObjectSceneDesc('globe_arcao', 'globe_arcao'),
    new FezArtObjectSceneDesc('globe_arch_bao', 'globe_arch_bao'),
    new FezArtObjectSceneDesc('globe_pillarao', 'globe_pillarao'),
    new FezArtObjectSceneDesc('globe_pivotao', 'globe_pivotao'),
    new FezArtObjectSceneDesc('globe_topao', 'globe_topao'),
    new FezArtObjectSceneDesc('globeao', 'globeao'),
    new FezArtObjectSceneDesc('grave_alcove_bao', 'grave_alcove_bao'),
    new FezArtObjectSceneDesc('grave_alcoveao', 'grave_alcoveao'),
    new FezArtObjectSceneDesc('grave_alcoveao_b', 'grave_alcoveao_b'),
    new FezArtObjectSceneDesc('grave_cabin_natureao', 'grave_cabin_natureao'),
    new FezArtObjectSceneDesc('grave_cabinao', 'grave_cabinao'),
    new FezArtObjectSceneDesc('grave_cubeao', 'grave_cubeao'),
    new FezArtObjectSceneDesc('grave_entranceao', 'grave_entranceao'),
    new FezArtObjectSceneDesc('grave_gateao', 'grave_gateao'),
    new FezArtObjectSceneDesc('grave_pillarao', 'grave_pillarao'),
    new FezArtObjectSceneDesc('greenboardao', 'greenboardao'),
    new FezArtObjectSceneDesc('hex_baseao', 'hex_baseao'),
    new FezArtObjectSceneDesc('hex_pillar_aao', 'hex_pillar_aao'),
    new FezArtObjectSceneDesc('hex_trigger_aao', 'hex_trigger_aao'),
    new FezArtObjectSceneDesc('hex_trigger_glowao', 'hex_trigger_glowao'),
    new FezArtObjectSceneDesc('hexahedron_1ao', 'hexahedron_1ao'),
    new FezArtObjectSceneDesc('hexahedron_monolithao', 'hexahedron_monolithao'),
    new FezArtObjectSceneDesc('hubdoors_bao', 'hubdoors_bao'),
    new FezArtObjectSceneDesc('hubdoorsao', 'hubdoorsao'),
    new FezArtObjectSceneDesc('huge_tree_orangeao', 'huge_tree_orangeao'),
    new FezArtObjectSceneDesc('huge_tree_pinkao', 'huge_tree_pinkao'),
    new FezArtObjectSceneDesc('huge_treeao', 'huge_treeao'),
    new FezArtObjectSceneDesc('indust_big_door_frameao', 'indust_big_door_frameao'),
    new FezArtObjectSceneDesc('indust_big_doorao', 'indust_big_doorao'),
    new FezArtObjectSceneDesc('indust_cave_metal_doorao', 'indust_cave_metal_doorao'),
    new FezArtObjectSceneDesc('indust_cave_stone_doorao', 'indust_cave_stone_doorao'),
    new FezArtObjectSceneDesc('indust_core_colorsao', 'indust_core_colorsao'),
    new FezArtObjectSceneDesc('indust_core_spinao', 'indust_core_spinao'),
    new FezArtObjectSceneDesc('indust_core_topao', 'indust_core_topao'),
    new FezArtObjectSceneDesc('indust_doorframe_aao', 'indust_doorframe_aao'),
    new FezArtObjectSceneDesc('indust_doorframe_bao', 'indust_doorframe_bao'),
    new FezArtObjectSceneDesc('industrial_door_frameao', 'industrial_door_frameao'),
    new FezArtObjectSceneDesc('industrial_girders_support_doubleao', 'industrial_girders_support_doubleao'),
    new FezArtObjectSceneDesc('industrial_girders_support_singleao', 'industrial_girders_support_singleao'),
    new FezArtObjectSceneDesc('int_base_drumao', 'int_base_drumao'),
    new FezArtObjectSceneDesc('int_bed_aao', 'int_bed_aao'),
    new FezArtObjectSceneDesc('int_boiler_nuzuao', 'int_boiler_nuzuao'),
    new FezArtObjectSceneDesc('int_boiler_pipe_nuzuao', 'int_boiler_pipe_nuzuao'),
    new FezArtObjectSceneDesc('int_boiler_pipeao', 'int_boiler_pipeao'),
    new FezArtObjectSceneDesc('int_boiler_table_nuzuao', 'int_boiler_table_nuzuao'),
    new FezArtObjectSceneDesc('int_boiler_tableao', 'int_boiler_tableao'),
    new FezArtObjectSceneDesc('int_boilerao', 'int_boilerao'),
    new FezArtObjectSceneDesc('int_ceiling_lamp_0ao', 'int_ceiling_lamp_0ao'),
    new FezArtObjectSceneDesc('int_ceiling_lamp_1ao', 'int_ceiling_lamp_1ao'),
    new FezArtObjectSceneDesc('int_chairao', 'int_chairao'),
    new FezArtObjectSceneDesc('int_crashao', 'int_crashao'),
    new FezArtObjectSceneDesc('int_fireplace_dao', 'int_fireplace_dao'),
    new FezArtObjectSceneDesc('int_fireplaceao', 'int_fireplaceao'),
    new FezArtObjectSceneDesc('int_floor_tomao', 'int_floor_tomao'),
    new FezArtObjectSceneDesc('int_fridgeao', 'int_fridgeao'),
    new FezArtObjectSceneDesc('int_grandfatherao', 'int_grandfatherao'),
    new FezArtObjectSceneDesc('int_hihatao', 'int_hihatao'),
    new FezArtObjectSceneDesc('int_kitchen_stuff0ao', 'int_kitchen_stuff0ao'),
    new FezArtObjectSceneDesc('int_kitchen_stuff1ao', 'int_kitchen_stuff1ao'),
    new FezArtObjectSceneDesc('int_kitchen_stuff2ao', 'int_kitchen_stuff2ao'),
    new FezArtObjectSceneDesc('int_kitchen_stuff3ao', 'int_kitchen_stuff3ao'),
    new FezArtObjectSceneDesc('int_metal_tableao', 'int_metal_tableao'),
    new FezArtObjectSceneDesc('int_mini_treeao', 'int_mini_treeao'),
    new FezArtObjectSceneDesc('int_mop_bucketao', 'int_mop_bucketao'),
    new FezArtObjectSceneDesc('int_mugao', 'int_mugao'),
    new FezArtObjectSceneDesc('int_ovenao', 'int_ovenao'),
    new FezArtObjectSceneDesc('int_parlor_books_aao', 'int_parlor_books_aao'),
    new FezArtObjectSceneDesc('int_parlor_booksao', 'int_parlor_booksao'),
    new FezArtObjectSceneDesc('int_parlor_chairao', 'int_parlor_chairao'),
    new FezArtObjectSceneDesc('int_parlor_passageao', 'int_parlor_passageao'),
    new FezArtObjectSceneDesc('int_parlor_poufao', 'int_parlor_poufao'),
    new FezArtObjectSceneDesc('int_potsao', 'int_potsao'),
    new FezArtObjectSceneDesc('int_shelfao', 'int_shelfao'),
    new FezArtObjectSceneDesc('int_sinkao', 'int_sinkao'),
    new FezArtObjectSceneDesc('int_snareao', 'int_snareao'),
    new FezArtObjectSceneDesc('int_stoolao', 'int_stoolao'),
    new FezArtObjectSceneDesc('int_table_aao', 'int_table_aao'),
    new FezArtObjectSceneDesc('int_tomsao', 'int_tomsao'),
    new FezArtObjectSceneDesc('jack_caseao', 'jack_caseao'),
    new FezArtObjectSceneDesc('jack_springao', 'jack_springao'),
    new FezArtObjectSceneDesc('lava_big_frameao', 'lava_big_frameao'),
    new FezArtObjectSceneDesc('lava_skullao', 'lava_skullao'),
    new FezArtObjectSceneDesc('lava_spin_1x1ao', 'lava_spin_1x1ao'),
    new FezArtObjectSceneDesc('lava_spin_2x1ao', 'lava_spin_2x1ao'),
    new FezArtObjectSceneDesc('lava_spin_2x2ao', 'lava_spin_2x2ao'),
    new FezArtObjectSceneDesc('lava_spin_2x2bao', 'lava_spin_2x2bao'),
    new FezArtObjectSceneDesc('lava_spin_3x1ao', 'lava_spin_3x1ao'),
    new FezArtObjectSceneDesc('lava_stone_door_frameao', 'lava_stone_door_frameao'),
    new FezArtObjectSceneDesc('lava_valveao', 'lava_valveao'),
    new FezArtObjectSceneDesc('ledge_aao', 'ledge_aao'),
    new FezArtObjectSceneDesc('ledge_bao', 'ledge_bao'),
    new FezArtObjectSceneDesc('lesser_gate__base_industao', 'lesser_gate__base_industao'),
    new FezArtObjectSceneDesc('lesser_gate_base_cmyao', 'lesser_gate_base_cmyao'),
    new FezArtObjectSceneDesc('lesser_gate_base_graveao', 'lesser_gate_base_graveao'),
    new FezArtObjectSceneDesc('lesser_gate_base_lavaao', 'lesser_gate_base_lavaao'),
    new FezArtObjectSceneDesc('lesser_gate_base_mineao', 'lesser_gate_base_mineao'),
    new FezArtObjectSceneDesc('lesser_gate_baseao', 'lesser_gate_baseao'),
    new FezArtObjectSceneDesc('lesser_gate_cmyao', 'lesser_gate_cmyao'),
    new FezArtObjectSceneDesc('lesser_gate_graveao', 'lesser_gate_graveao'),
    new FezArtObjectSceneDesc('lesser_gate_industao', 'lesser_gate_industao'),
    new FezArtObjectSceneDesc('lesser_gate_lavaao', 'lesser_gate_lavaao'),
    new FezArtObjectSceneDesc('lesser_gate_mineao', 'lesser_gate_mineao'),
    new FezArtObjectSceneDesc('lesser_gate_zuao', 'lesser_gate_zuao'),
    new FezArtObjectSceneDesc('lesser_gateao', 'lesser_gateao'),
    new FezArtObjectSceneDesc('letter_cubeao', 'letter_cubeao'),
    new FezArtObjectSceneDesc('lib_int_doorao', 'lib_int_doorao'),
    new FezArtObjectSceneDesc('lib_int_pillarao', 'lib_int_pillarao'),
    new FezArtObjectSceneDesc('lib_stone_pillarao', 'lib_stone_pillarao'),
    new FezArtObjectSceneDesc('library_coreao', 'library_coreao'),
    new FezArtObjectSceneDesc('library_deskao', 'library_deskao'),
    new FezArtObjectSceneDesc('library_doorao', 'library_doorao'),
    new FezArtObjectSceneDesc('library_fireplaceao', 'library_fireplaceao'),
    new FezArtObjectSceneDesc('library_pillar_aao', 'library_pillar_aao'),
    new FezArtObjectSceneDesc('library_pillarao', 'library_pillarao'),
    new FezArtObjectSceneDesc('library_pyramidao', 'library_pyramidao'),
    new FezArtObjectSceneDesc('library_roofao', 'library_roofao'),
    new FezArtObjectSceneDesc('lifesaverao', 'lifesaverao'),
    new FezArtObjectSceneDesc('lighthouse_aao', 'lighthouse_aao'),
    new FezArtObjectSceneDesc('lighthouse_coreao', 'lighthouse_coreao'),
    new FezArtObjectSceneDesc('lighthouse_int_doorao', 'lighthouse_int_doorao'),
    new FezArtObjectSceneDesc('lighthouse_platform_aao', 'lighthouse_platform_aao'),
    new FezArtObjectSceneDesc('lighthouse_spin_aao', 'lighthouse_spin_aao'),
    new FezArtObjectSceneDesc('lighthouse_testao', 'lighthouse_testao'),
    new FezArtObjectSceneDesc('lighthouse_topao', 'lighthouse_topao'),
    new FezArtObjectSceneDesc('locker_benchao', 'locker_benchao'),
    new FezArtObjectSceneDesc('lockerao', 'lockerao'),
    new FezArtObjectSceneDesc('marker_fourao', 'marker_fourao'),
    new FezArtObjectSceneDesc('marker_oneao', 'marker_oneao'),
    new FezArtObjectSceneDesc('marker_threeao', 'marker_threeao'),
    new FezArtObjectSceneDesc('marker_twoao', 'marker_twoao'),
    new FezArtObjectSceneDesc('math_doorao', 'math_doorao'),
    new FezArtObjectSceneDesc('mausoleum_cryptao', 'mausoleum_cryptao'),
    new FezArtObjectSceneDesc('mausoleum_pillars_cryptao', 'mausoleum_pillars_cryptao'),
    new FezArtObjectSceneDesc('mausoleum_pillarsao', 'mausoleum_pillarsao'),
    new FezArtObjectSceneDesc('mausoleumao', 'mausoleumao'),
    new FezArtObjectSceneDesc('mech_5x5ao', 'mech_5x5ao'),
    new FezArtObjectSceneDesc('mech_support_aao', 'mech_support_aao'),
    new FezArtObjectSceneDesc('megalithao', 'megalithao'),
    new FezArtObjectSceneDesc('memory_core_signageao', 'memory_core_signageao'),
    new FezArtObjectSceneDesc('menu_cube_cmy', 'menu_cube_cmy'),
    new FezArtObjectSceneDesc('menu_cube_gb', 'menu_cube_gb'),
    new FezArtObjectSceneDesc('menu_cube_virtual', 'menu_cube_virtual'),
    new FezArtObjectSceneDesc('menu_cubeao', 'menu_cubeao'),
    new FezArtObjectSceneDesc('mine_big_crateao', 'mine_big_crateao'),
    new FezArtObjectSceneDesc('mine_city_big_doorao', 'mine_city_big_doorao'),
    new FezArtObjectSceneDesc('mine_city_door_baseao', 'mine_city_door_baseao'),
    new FezArtObjectSceneDesc('mine_city_door_tubeao', 'mine_city_door_tubeao'),
    new FezArtObjectSceneDesc('mine_doorao', 'mine_doorao'),
    new FezArtObjectSceneDesc('mine_entrance_aao', 'mine_entrance_aao'),
    new FezArtObjectSceneDesc('mine_entrance_bao', 'mine_entrance_bao'),
    new FezArtObjectSceneDesc('mine_entrance_cao', 'mine_entrance_cao'),
    new FezArtObjectSceneDesc('mine_tools_0ao', 'mine_tools_0ao'),
    new FezArtObjectSceneDesc('mine_tools_1ao', 'mine_tools_1ao'),
    new FezArtObjectSceneDesc('mine_tools_2ao', 'mine_tools_2ao'),
    new FezArtObjectSceneDesc('minecart_aao', 'minecart_aao'),
    new FezArtObjectSceneDesc('monolithao', 'monolithao'),
    new FezArtObjectSceneDesc('moss_aao', 'moss_aao'),
    new FezArtObjectSceneDesc('mothercubeao', 'mothercubeao'),
    new FezArtObjectSceneDesc('neon_cablesao', 'neon_cablesao'),
    new FezArtObjectSceneDesc('neon_foodao', 'neon_foodao'),
    new FezArtObjectSceneDesc('neon_frame_aao', 'neon_frame_aao'),
    new FezArtObjectSceneDesc('neon_frame_bao', 'neon_frame_bao'),
    new FezArtObjectSceneDesc('neon_frame_cao', 'neon_frame_cao'),
    new FezArtObjectSceneDesc('neon_frame_dao', 'neon_frame_dao'),
    new FezArtObjectSceneDesc('neon_goodao', 'neon_goodao'),
    new FezArtObjectSceneDesc('neon_hardao', 'neon_hardao'),
    new FezArtObjectSceneDesc('neon_nuao', 'neon_nuao'),
    new FezArtObjectSceneDesc('neon_supportao', 'neon_supportao'),
    new FezArtObjectSceneDesc('neon_workao', 'neon_workao'),
    new FezArtObjectSceneDesc('neon_zuao', 'neon_zuao'),
    new FezArtObjectSceneDesc('new_hexao', 'new_hexao'),
    new FezArtObjectSceneDesc('new_minecartao', 'new_minecartao'),
    new FezArtObjectSceneDesc('newhouse_aao', 'newhouse_aao'),
    new FezArtObjectSceneDesc('newhouse_bao', 'newhouse_bao'),
    new FezArtObjectSceneDesc('newshroomao', 'newshroomao'),
    new FezArtObjectSceneDesc('number_cubeao', 'number_cubeao'),
    new FezArtObjectSceneDesc('nutao', 'nutao'),
    new FezArtObjectSceneDesc('nutbolt_base_underao', 'nutbolt_base_underao'),
    new FezArtObjectSceneDesc('nutbolt_baseao', 'nutbolt_baseao'),
    new FezArtObjectSceneDesc('nutbolt_cap_bao', 'nutbolt_cap_bao'),
    new FezArtObjectSceneDesc('nutbolt_capao', 'nutbolt_capao'),
    new FezArtObjectSceneDesc('nuzu_benchao', 'nuzu_benchao'),
    new FezArtObjectSceneDesc('nuzu_big_doorao', 'nuzu_big_doorao'),
    new FezArtObjectSceneDesc('nuzu_sewer_barsao', 'nuzu_sewer_barsao'),
    new FezArtObjectSceneDesc('nuzu_signao', 'nuzu_signao'),
    new FezArtObjectSceneDesc('nuzu_watertowerao', 'nuzu_watertowerao'),
    new FezArtObjectSceneDesc('obs_dome_aao', 'obs_dome_aao'),
    new FezArtObjectSceneDesc('obs_dome_bao', 'obs_dome_bao'),
    new FezArtObjectSceneDesc('obs_dome_cao', 'obs_dome_cao'),
    new FezArtObjectSceneDesc('obs_dome_dao', 'obs_dome_dao'),
    new FezArtObjectSceneDesc('observatory_doorframeao', 'observatory_doorframeao'),
    new FezArtObjectSceneDesc('oldschool_desk_grassao', 'oldschool_desk_grassao'),
    new FezArtObjectSceneDesc('oldschool_deskao', 'oldschool_deskao'),
    new FezArtObjectSceneDesc('orange_piston_shaftao', 'orange_piston_shaftao'),
    new FezArtObjectSceneDesc('orange_pistonao', 'orange_pistonao'),
    new FezArtObjectSceneDesc('orr_cog_lao', 'orr_cog_lao'),
    new FezArtObjectSceneDesc('orr_cog_mao', 'orr_cog_mao'),
    new FezArtObjectSceneDesc('orr_cog_sao', 'orr_cog_sao'),
    new FezArtObjectSceneDesc('orr_earth_branchao', 'orr_earth_branchao'),
    new FezArtObjectSceneDesc('orr_earthao', 'orr_earthao'),
    new FezArtObjectSceneDesc('orr_moon_branchao', 'orr_moon_branchao'),
    new FezArtObjectSceneDesc('orr_moonao', 'orr_moonao'),
    new FezArtObjectSceneDesc('orr_planet_wao', 'orr_planet_wao'),
    new FezArtObjectSceneDesc('orr_sun_branchao', 'orr_sun_branchao'),
    new FezArtObjectSceneDesc('orr_sunao', 'orr_sunao'),
    new FezArtObjectSceneDesc('orr_w_branchao', 'orr_w_branchao'),
    new FezArtObjectSceneDesc('owl_base_fillerao', 'owl_base_fillerao'),
    new FezArtObjectSceneDesc('owl_baseao', 'owl_baseao'),
    new FezArtObjectSceneDesc('owl_statue_body_ao', 'owl_statue_body_ao'),
    new FezArtObjectSceneDesc('owl_statue_drapes_bao', 'owl_statue_drapes_bao'),
    new FezArtObjectSceneDesc('owl_statue_drapesao', 'owl_statue_drapesao'),
    new FezArtObjectSceneDesc('owl_statue_headao', 'owl_statue_headao'),
    new FezArtObjectSceneDesc('owl_statueao', 'owl_statueao'),
    new FezArtObjectSceneDesc('piston_big_baseao', 'piston_big_baseao'),
    new FezArtObjectSceneDesc('piston_bigao', 'piston_bigao'),
    new FezArtObjectSceneDesc('pivot_base_ind_caveao', 'pivot_base_ind_caveao'),
    new FezArtObjectSceneDesc('pivot_base_redao', 'pivot_base_redao'),
    new FezArtObjectSceneDesc('pivot_base_yellowao', 'pivot_base_yellowao'),
    new FezArtObjectSceneDesc('pivot_baseao', 'pivot_baseao'),
    new FezArtObjectSceneDesc('pivot_ind_caveao', 'pivot_ind_caveao'),
    new FezArtObjectSceneDesc('pivot_redao', 'pivot_redao'),
    new FezArtObjectSceneDesc('pivot_yellowao', 'pivot_yellowao'),
    new FezArtObjectSceneDesc('pivotao', 'pivotao'),
    new FezArtObjectSceneDesc('pneumaticao', 'pneumaticao'),
    new FezArtObjectSceneDesc('pyramid_banner_aao', 'pyramid_banner_aao'),
    new FezArtObjectSceneDesc('pyramid_banner_bao', 'pyramid_banner_bao'),
    new FezArtObjectSceneDesc('pyramid_banner_cao', 'pyramid_banner_cao'),
    new FezArtObjectSceneDesc('pyramid_banner_torn_aao', 'pyramid_banner_torn_aao'),
    new FezArtObjectSceneDesc('pyramid_banner_torn_bao', 'pyramid_banner_torn_bao'),
    new FezArtObjectSceneDesc('pyramid_banner_torn_cao', 'pyramid_banner_torn_cao'),
    new FezArtObjectSceneDesc('pyramid_statue_owlao', 'pyramid_statue_owlao'),
    new FezArtObjectSceneDesc('pyramid_statueao', 'pyramid_statueao'),
    new FezArtObjectSceneDesc('qr_cube_foxao', 'qr_cube_foxao'),
    new FezArtObjectSceneDesc('rebuilding_hexahedronao', 'rebuilding_hexahedronao'),
    new FezArtObjectSceneDesc('reservoirao', 'reservoirao'),
    new FezArtObjectSceneDesc('roots_roots_aao', 'roots_roots_aao'),
    new FezArtObjectSceneDesc('roots_roots_bao', 'roots_roots_bao'),
    new FezArtObjectSceneDesc('rotato_1x1ao', 'rotato_1x1ao'),
    new FezArtObjectSceneDesc('rotato_3x3ao', 'rotato_3x3ao'),
    new FezArtObjectSceneDesc('rotato_longao', 'rotato_longao'),
    new FezArtObjectSceneDesc('save_cube_baseao', 'save_cube_baseao'),
    new FezArtObjectSceneDesc('save_cubeao', 'save_cubeao'),
    new FezArtObjectSceneDesc('scaffolding_aao', 'scaffolding_aao'),
    new FezArtObjectSceneDesc('secret_graveao', 'secret_graveao'),
    new FezArtObjectSceneDesc('secret_memoryao', 'secret_memoryao'),
    new FezArtObjectSceneDesc('secret_metal_bao', 'secret_metal_bao'),
    new FezArtObjectSceneDesc('secret_metal_darkao', 'secret_metal_darkao'),
    new FezArtObjectSceneDesc('secret_metalao', 'secret_metalao'),
    new FezArtObjectSceneDesc('secret_mineao', 'secret_mineao'),
    new FezArtObjectSceneDesc('secret_nuzu_abao', 'secret_nuzu_abao'),
    new FezArtObjectSceneDesc('secret_obsao', 'secret_obsao'),
    new FezArtObjectSceneDesc('secret_sewer_bao', 'secret_sewer_bao'),
    new FezArtObjectSceneDesc('secret_sewerao', 'secret_sewerao'),
    new FezArtObjectSceneDesc('secret_throneao', 'secret_throneao'),
    new FezArtObjectSceneDesc('secret_treeao', 'secret_treeao'),
    new FezArtObjectSceneDesc('secret_visitorao', 'secret_visitorao'),
    new FezArtObjectSceneDesc('secret_wallao', 'secret_wallao'),
    new FezArtObjectSceneDesc('secret_whiteao', 'secret_whiteao'),
    new FezArtObjectSceneDesc('secret_zu_cityao', 'secret_zu_cityao'),
    new FezArtObjectSceneDesc('sentinel_wallao', 'sentinel_wallao'),
    new FezArtObjectSceneDesc('sewer_bars_aao', 'sewer_bars_aao'),
    new FezArtObjectSceneDesc('sewer_big_mouthao', 'sewer_big_mouthao'),
    new FezArtObjectSceneDesc('sewer_core_frameao', 'sewer_core_frameao'),
    new FezArtObjectSceneDesc('sewer_door_frame_bao', 'sewer_door_frame_bao'),
    new FezArtObjectSceneDesc('sewer_doorao', 'sewer_doorao'),
    new FezArtObjectSceneDesc('sewer_lava_doorao', 'sewer_lava_doorao'),
    new FezArtObjectSceneDesc('sewer_lava_frameao', 'sewer_lava_frameao'),
    new FezArtObjectSceneDesc('sewer_lesser_gate_baseao', 'sewer_lesser_gate_baseao'),
    new FezArtObjectSceneDesc('sewer_lesser_gateao', 'sewer_lesser_gateao'),
    new FezArtObjectSceneDesc('sewer_outao', 'sewer_outao'),
    new FezArtObjectSceneDesc('sewer_pivot_baseao', 'sewer_pivot_baseao'),
    new FezArtObjectSceneDesc('sewer_pivot_topao', 'sewer_pivot_topao'),
    new FezArtObjectSceneDesc('sewer_qr_cube_sonyao', 'sewer_qr_cube_sonyao'),
    new FezArtObjectSceneDesc('sewer_qr_cubeao', 'sewer_qr_cubeao'),
    new FezArtObjectSceneDesc('sewer_treasure_bottomao', 'sewer_treasure_bottomao'),
    new FezArtObjectSceneDesc('sewer_treasure_topao', 'sewer_treasure_topao'),
    new FezArtObjectSceneDesc('sewer_valveao', 'sewer_valveao'),
    new FezArtObjectSceneDesc('shower_headao', 'shower_headao'),
    new FezArtObjectSceneDesc('skull_bao', 'skull_bao'),
    new FezArtObjectSceneDesc('skull_jawao', 'skull_jawao'),
    new FezArtObjectSceneDesc('skullao', 'skullao'),
    new FezArtObjectSceneDesc('skulldoorao', 'skulldoorao'),
    new FezArtObjectSceneDesc('spin_red_1x1ao', 'spin_red_1x1ao'),
    new FezArtObjectSceneDesc('spin_red_2x1ao', 'spin_red_2x1ao'),
    new FezArtObjectSceneDesc('spin_red_2x2_offcenterao', 'spin_red_2x2_offcenterao'),
    new FezArtObjectSceneDesc('spin_red_3x11ao', 'spin_red_3x11ao'),
    new FezArtObjectSceneDesc('spinblock_aao', 'spinblock_aao'),
    new FezArtObjectSceneDesc('spinwall_aao', 'spinwall_aao'),
    new FezArtObjectSceneDesc('spiretree_topao', 'spiretree_topao'),
    new FezArtObjectSceneDesc('spiretree_trunkao', 'spiretree_trunkao'),
    new FezArtObjectSceneDesc('split_up_cubeao', 'split_up_cubeao'),
    new FezArtObjectSceneDesc('squid_eye_bigao', 'squid_eye_bigao'),
    new FezArtObjectSceneDesc('squid_eye_smallao', 'squid_eye_smallao'),
    new FezArtObjectSceneDesc('squid_pillar_aao', 'squid_pillar_aao'),
    new FezArtObjectSceneDesc('squid_statue_smallao', 'squid_statue_smallao'),
    new FezArtObjectSceneDesc('stargate_aao', 'stargate_aao'),
    new FezArtObjectSceneDesc('stargate_bao', 'stargate_bao'),
    new FezArtObjectSceneDesc('stargate_pyramid_aao', 'stargate_pyramid_aao'),
    new FezArtObjectSceneDesc('stargate_pyramid_bao', 'stargate_pyramid_bao'),
    new FezArtObjectSceneDesc('stargate_ring_aao', 'stargate_ring_aao'),
    new FezArtObjectSceneDesc('stargate_ring_bao', 'stargate_ring_bao'),
    new FezArtObjectSceneDesc('stargate_ring_cao', 'stargate_ring_cao'),
    new FezArtObjectSceneDesc('stargate_ring_dao', 'stargate_ring_dao'),
    new FezArtObjectSceneDesc('stargate_ruin_aao', 'stargate_ruin_aao'),
    new FezArtObjectSceneDesc('stargate_ruin_bao', 'stargate_ruin_bao'),
    new FezArtObjectSceneDesc('stargate_ruin_cao', 'stargate_ruin_cao'),
    new FezArtObjectSceneDesc('stargate_sao', 'stargate_sao'),
    new FezArtObjectSceneDesc('stone_door_frameao', 'stone_door_frameao'),
    new FezArtObjectSceneDesc('student_deskao', 'student_deskao'),
    new FezArtObjectSceneDesc('tall_tree_aao', 'tall_tree_aao'),
    new FezArtObjectSceneDesc('teacher_desk_nuzuao', 'teacher_desk_nuzuao'),
    new FezArtObjectSceneDesc('teacher_deskao', 'teacher_deskao'),
    new FezArtObjectSceneDesc('telescope_lenseao', 'telescope_lenseao'),
    new FezArtObjectSceneDesc('telescope_seatao', 'telescope_seatao'),
    new FezArtObjectSceneDesc('telescopeao', 'telescopeao'),
    new FezArtObjectSceneDesc('tetris_entranceao', 'tetris_entranceao'),
    new FezArtObjectSceneDesc('tetris_puzzle_baseao', 'tetris_puzzle_baseao'),
    new FezArtObjectSceneDesc('throne_aao', 'throne_aao'),
    new FezArtObjectSceneDesc('throne_bao', 'throne_bao'),
    new FezArtObjectSceneDesc('throne_thingao', 'throne_thingao'),
    new FezArtObjectSceneDesc('timeswitch_baseao', 'timeswitch_baseao'),
    new FezArtObjectSceneDesc('timeswitch_coreao', 'timeswitch_coreao'),
    new FezArtObjectSceneDesc('timeswitch_postao', 'timeswitch_postao'),
    new FezArtObjectSceneDesc('tiny_chapeauao', 'tiny_chapeauao'),
    new FezArtObjectSceneDesc('tombstoneao', 'tombstoneao'),
    new FezArtObjectSceneDesc('tome_bao', 'tome_bao'),
    new FezArtObjectSceneDesc('tome_coverao', 'tome_coverao'),
    new FezArtObjectSceneDesc('tomeao', 'tomeao'),
    new FezArtObjectSceneDesc('totem_bao', 'totem_bao'),
    new FezArtObjectSceneDesc('totemao', 'totemao'),
    new FezArtObjectSceneDesc('towerblockao', 'towerblockao'),
    new FezArtObjectSceneDesc('tracks0ao', 'tracks0ao'),
    new FezArtObjectSceneDesc('tracks1ao', 'tracks1ao'),
    new FezArtObjectSceneDesc('tracks2ao', 'tracks2ao'),
    new FezArtObjectSceneDesc('trappedao', 'trappedao'),
    new FezArtObjectSceneDesc('trashcan_lidao', 'trashcan_lidao'),
    new FezArtObjectSceneDesc('trashcan_sideao', 'trashcan_sideao'),
    new FezArtObjectSceneDesc('trashcanao', 'trashcanao'),
    new FezArtObjectSceneDesc('treasure_mapao', 'treasure_mapao'),
    new FezArtObjectSceneDesc('treasure_virtual_bottomao', 'treasure_virtual_bottomao'),
    new FezArtObjectSceneDesc('treasure_virtual_topao', 'treasure_virtual_topao'),
    new FezArtObjectSceneDesc('treasureao', 'treasureao'),
    new FezArtObjectSceneDesc('treasurebottomao', 'treasurebottomao'),
    new FezArtObjectSceneDesc('treasuretopao', 'treasuretopao'),
    new FezArtObjectSceneDesc('tree_of_deathao', 'tree_of_deathao'),
    new FezArtObjectSceneDesc('tri_skullao', 'tri_skullao'),
    new FezArtObjectSceneDesc('up_signao', 'up_signao'),
    new FezArtObjectSceneDesc('village_big_crateao', 'village_big_crateao'),
    new FezArtObjectSceneDesc('village_tankao', 'village_tankao'),
    new FezArtObjectSceneDesc('visitor_aao', 'visitor_aao'),
    new FezArtObjectSceneDesc('visitor_bao', 'visitor_bao'),
    new FezArtObjectSceneDesc('visitor_cao', 'visitor_cao'),
    new FezArtObjectSceneDesc('visitor_dao', 'visitor_dao'),
    new FezArtObjectSceneDesc('wall_entranceao', 'wall_entranceao'),
    new FezArtObjectSceneDesc('walldoor_aao', 'walldoor_aao'),
    new FezArtObjectSceneDesc('walldoor_bao', 'walldoor_bao'),
    new FezArtObjectSceneDesc('wallwindow_aao', 'wallwindow_aao'),
    new FezArtObjectSceneDesc('wallwindow_bao', 'wallwindow_bao'),
    new FezArtObjectSceneDesc('wallwindow_cao', 'wallwindow_cao'),
    new FezArtObjectSceneDesc('warning_signao', 'warning_signao'),
    new FezArtObjectSceneDesc('warproom_postaao', 'warproom_postaao'),
    new FezArtObjectSceneDesc('water_doorframe_bao', 'water_doorframe_bao'),
    new FezArtObjectSceneDesc('water_doorframeao', 'water_doorframeao'),
    new FezArtObjectSceneDesc('water_statue_baseao', 'water_statue_baseao'),
    new FezArtObjectSceneDesc('water_statueao', 'water_statueao'),
    new FezArtObjectSceneDesc('water_tower_legsao', 'water_tower_legsao'),
    new FezArtObjectSceneDesc('water_towerao', 'water_towerao'),
    new FezArtObjectSceneDesc('water_valve_podiumao', 'water_valve_podiumao'),
    new FezArtObjectSceneDesc('waterfall_head_eye_aao', 'waterfall_head_eye_aao'),
    new FezArtObjectSceneDesc('waterfall_head_eye_bao', 'waterfall_head_eye_bao'),
    new FezArtObjectSceneDesc('waterfall_head_mouthao', 'waterfall_head_mouthao'),
    new FezArtObjectSceneDesc('waterfall_headao', 'waterfall_headao'),
    new FezArtObjectSceneDesc('waterfall_support_aao', 'waterfall_support_aao'),
    new FezArtObjectSceneDesc('waterfall_support_bao', 'waterfall_support_bao'),
    new FezArtObjectSceneDesc('waterfall_support_cao', 'waterfall_support_cao'),
    new FezArtObjectSceneDesc('watertower_owl_body_ao', 'watertower_owl_body_ao'),
    new FezArtObjectSceneDesc('watertower_owl_bodyao', 'watertower_owl_bodyao'),
    new FezArtObjectSceneDesc('watertower_owl_head_ao', 'watertower_owl_head_ao'),
    new FezArtObjectSceneDesc('watertower_owl_headao', 'watertower_owl_headao'),
    new FezArtObjectSceneDesc('waterwheel_baseao', 'waterwheel_baseao'),
    new FezArtObjectSceneDesc('waterwheelao', 'waterwheelao'),
    new FezArtObjectSceneDesc('weight_switch_baseao', 'weight_switch_baseao'),
    new FezArtObjectSceneDesc('wellao', 'wellao'),
    new FezArtObjectSceneDesc('white_watermouthao', 'white_watermouthao'),
    new FezArtObjectSceneDesc('windmill_bao', 'windmill_bao'),
    new FezArtObjectSceneDesc('windmill_core_aao', 'windmill_core_aao'),
    new FezArtObjectSceneDesc('windmill_core_bao', 'windmill_core_bao'),
    new FezArtObjectSceneDesc('windmill_core_cao', 'windmill_core_cao'),
    new FezArtObjectSceneDesc('windmill_int_aao', 'windmill_int_aao'),
    new FezArtObjectSceneDesc('windmill_int_bao', 'windmill_int_bao'),
    new FezArtObjectSceneDesc('windmill_int_cao', 'windmill_int_cao'),
    new FezArtObjectSceneDesc('windmill_int_dao', 'windmill_int_dao'),
    new FezArtObjectSceneDesc('windmillao', 'windmillao'),
    new FezArtObjectSceneDesc('wooden_door_frameao', 'wooden_door_frameao'),
    new FezArtObjectSceneDesc('woodhouse_aao', 'woodhouse_aao'),
    new FezArtObjectSceneDesc('yu_statue_aao', 'yu_statue_aao'),
    new FezArtObjectSceneDesc('yu_statue_bao', 'yu_statue_bao'),
    new FezArtObjectSceneDesc('zu_bazaar_0ao', 'zu_bazaar_0ao'),
    new FezArtObjectSceneDesc('zu_bazaar_1ao', 'zu_bazaar_1ao'),
    new FezArtObjectSceneDesc('zu_bazaar_2ao', 'zu_bazaar_2ao'),
    new FezArtObjectSceneDesc('zu_bazaar_3ao', 'zu_bazaar_3ao'),
    new FezArtObjectSceneDesc('zu_bustao', 'zu_bustao'),
    new FezArtObjectSceneDesc('zu_city_big_doorframeao', 'zu_city_big_doorframeao'),
    new FezArtObjectSceneDesc('zu_city_door_pao', 'zu_city_door_pao'),
    new FezArtObjectSceneDesc('zu_city_doorao', 'zu_city_doorao'),
    new FezArtObjectSceneDesc('zu_city_waterfaceao', 'zu_city_waterfaceao'),
    new FezArtObjectSceneDesc('zu_city_watermouthao', 'zu_city_watermouthao'),
    new FezArtObjectSceneDesc('zu_city_window_pao', 'zu_city_window_pao'),
    new FezArtObjectSceneDesc('zu_city_windowao', 'zu_city_windowao'),
    new FezArtObjectSceneDesc('zu_door_frameao', 'zu_door_frameao'),
    new FezArtObjectSceneDesc('zu_doorao', 'zu_doorao'),
    new FezArtObjectSceneDesc('zu_gateao', 'zu_gateao'),
    new FezArtObjectSceneDesc('zu_house_doorao', 'zu_house_doorao'),
    new FezArtObjectSceneDesc('zu_kiosk_aao', 'zu_kiosk_aao'),
    new FezArtObjectSceneDesc('zu_kiosk_bao', 'zu_kiosk_bao'),
    new FezArtObjectSceneDesc('zu_kiosk_cao', 'zu_kiosk_cao'),
    new FezArtObjectSceneDesc('zu_lao', 'zu_lao'),
    new FezArtObjectSceneDesc('zu_secret_entranceao', 'zu_secret_entranceao'),
    new FezArtObjectSceneDesc('zu_signao', 'zu_signao'),
    new FezArtObjectSceneDesc('zu_stone_door_frameao', 'zu_stone_door_frameao'),
    new FezArtObjectSceneDesc('zu_tao', 'zu_tao'),
    new FezArtObjectSceneDesc('zu_window_barsao', 'zu_window_barsao'),
    new FezArtObjectSceneDesc('zu_zao', 'zu_zao'),
    new FezArtObjectSceneDesc('zuhead_a_w_gao', 'zuhead_a_w_gao'),
    new FezArtObjectSceneDesc('zuhead_a_wao', 'zuhead_a_wao'),
    new FezArtObjectSceneDesc('zuhead_aao', 'zuhead_aao'),
    new FezArtObjectSceneDesc('zuhead_b_w_gao', 'zuhead_b_w_gao'),
    new FezArtObjectSceneDesc('zuhead_b_wao', 'zuhead_b_wao'),
    new FezArtObjectSceneDesc('zuhead_bao', 'zuhead_bao'),
    new FezArtObjectSceneDesc('zuish_monolith_aao', 'zuish_monolith_aao'),
    new FezArtObjectSceneDesc('zuon_bodyao', 'zuon_bodyao'),
    new FezArtObjectSceneDesc('zuon_eyeao', 'zuon_eyeao'),
    new FezArtObjectSceneDesc('zuon_headao', 'zuon_headao'),
    new FezArtObjectSceneDesc('zuon_legsao', 'zuon_legsao'),
];

export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs };
