
import * as Viewer from '../viewer.js';
import { DataFetcher } from '../DataFetcher.js';
import { GfxDevice, GfxTexture } from '../gfx/platform/GfxPlatform.js';
import { SceneContext } from '../SceneBase.js';
import { FezRenderer, FezArtObjectRenderer } from './FezRenderer.js';
import { TrilesetData } from './TrileData.js';
import { ArtObjectData } from './ArtObjectData.js';
import { BackgroundPlaneData } from './BackgroundPlaneData.js';
import { GfxRenderCache } from '../gfx/render/GfxRenderCache.js';
import { SkyData } from './Sky.js';
import { FezContentTypeReaderManager, Fez_ArtObject, Fez_TrileSet, Fez_AnimatedTexture, Fez_Level } from './XNB_Fez.js';
import { parse, XNA_Texture2D } from './XNB.js';
import { makeTextureFromXNA_Texture2D } from './Texture.js';
import { assertExists } from '../util.js';

const pathBase = 'Fez';

export class ModelCache {
    public promiseCache = new Map<string, Promise<void>>();
    public trilesetDatas: TrilesetData[] = [];
    public artObjectDatas: ArtObjectData[] = [];
    public backgroundPlaneDatas: BackgroundPlaneData[] = [];
    public skyDatas: SkyData[] = [];
    public textureCache = new Map<string, GfxTexture>();
    public renderCache: GfxRenderCache;
    private fezTypeReaderManager = new FezContentTypeReaderManager();

    constructor(device: GfxDevice, private dataFetcher: DataFetcher) {
        this.renderCache = new GfxRenderCache(device);
    }

    public waitForLoad(): Promise<void> {
        return Promise.all(this.promiseCache.values()) as unknown as Promise<void>;
    }

    public async fetchXNB<T>(path: string): Promise<T> {
        const data = await this.dataFetcher.fetchData(`${pathBase}/${path.toLowerCase()}`);
        return parse<T>(this.fezTypeReaderManager, data);
    }

    private async fetchTrilesetInternal(path: string): Promise<void> {
        const device = this.renderCache.device;
        const data = await this.fetchXNB<Fez_TrileSet>(`xnb/trile sets/${path}.xnb`);
        this.trilesetDatas.push(new TrilesetData(device, this.renderCache, path, data));
    }

    private async fetchArtObjectInternal(path: string): Promise<void> {
        const device = this.renderCache.device;
        const xnb = await this.fetchXNB<Fez_ArtObject>(`xnb/art objects/${path}.xnb`);
        this.artObjectDatas.push(new ArtObjectData(device, this.renderCache, path, xnb));
    }

    private async fetchBackgroundPlaneInternal(path: string, isAnimated: boolean): Promise<void> {
        const device = this.renderCache.device;
        if (isAnimated) {
            const data = await this.fetchXNB<Fez_AnimatedTexture>(`xnb/background planes/${path}.xnb`);
            this.backgroundPlaneDatas.push(new BackgroundPlaneData(device, path, data.texture, data));
        } else {
            const data = await this.fetchXNB<XNA_Texture2D>(`xnb/background planes/${path}.xnb`);
            this.backgroundPlaneDatas.push(new BackgroundPlaneData(device, path, data, null));
        }
    }

    private async fetchSkyDataInternal(path: string): Promise<void> {
        this.skyDatas.push(await SkyData.fetch(this, path));
    }

    private async fetchTextureInternal(path: string): Promise<void> {
        const device = this.renderCache.device;
        const tex = await this.fetchXNB<XNA_Texture2D>(path);
        const gfxTexture = makeTextureFromXNA_Texture2D(device, tex);
        this.textureCache.set(path, gfxTexture);
    }

    public requestTrileset(path: string): void {
        const key = `trile sets/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchTrilesetInternal(path));
    }

    public requestArtObject(path: string): void {
        const key = `art objects/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchArtObjectInternal(path));
    }

    public requestBackgroundPlane(path: string, isAnimated: boolean): void {
        const key = `background planes/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchBackgroundPlaneInternal(path, isAnimated));
    }

    public requestSky(path: string): void {
        const key = `skies/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchSkyDataInternal(path));
    }

    public requestTexture(path: string): Promise<void> {
        const key = `textures/${path}`;
        if (!this.promiseCache.has(key))
            this.promiseCache.set(key, this.fetchTextureInternal(path));
        return this.promiseCache.get(key)!;
    }

    public getTexture(path: string): GfxTexture {
        return assertExists(this.textureCache.get(path));
    }

    public destroy(device: GfxDevice): void {
        this.renderCache.destroy();
        for (let i = 0; i < this.trilesetDatas.length; i++)
            this.trilesetDatas[i].destroy(device);
        for (let i = 0; i < this.artObjectDatas.length; i++)
            this.artObjectDatas[i].destroy(device);
        for (let i = 0; i < this.backgroundPlaneDatas.length; i++)
            this.backgroundPlaneDatas[i].destroy(device);
        for (let i = 0; i < this.skyDatas.length; i++)
            this.skyDatas[i].destroy(device);
        for (const texture of this.textureCache.values())
            device.destroyTexture(texture);
    }
}

class FezSceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string) {
    }

    public async createScene(device: GfxDevice, context: SceneContext): Promise<Viewer.SceneGfx> {
        const cache = await context.dataShare.ensureObject<ModelCache>(`${pathBase}/ModelCache`, async () => {
            return new ModelCache(device, context.dataFetcher);
        });

        const levelName = this.id.substring('levels/'.length);
        const level = await cache.fetchXNB<Fez_Level>(`xnb/levels/${levelName}.xnb`);

        cache.requestTrileset(level.trileSetName);
        cache.requestSky(level.skyName);

        for (const artObject of level.artObjects.values())
            cache.requestArtObject(artObject.name);

        for (const backgroundPlane of level.backgroundPlanes.values())
            cache.requestBackgroundPlane(backgroundPlane.textureName, backgroundPlane.animated);

        await cache.waitForLoad();

        return new FezRenderer(device, cache, level);
    }
}

class FezArtObjectSceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string) {
    }

    public async createScene(device: GfxDevice, context: SceneContext): Promise<Viewer.SceneGfx> {
        const cache = await context.dataShare.ensureObject<ModelCache>(`${pathBase}/ModelCache`, async () => {
            return new ModelCache(device, context.dataFetcher);
        });

        const artObjectName = this.id.substring('art_objects/'.length);
        const xnb = await cache.fetchXNB<Fez_ArtObject>(`xnb/art objects/${artObjectName}.xnb`);
        const artObjectData = new ArtObjectData(device, cache.renderCache, artObjectName, xnb);
        return new FezArtObjectRenderer(device, artObjectData);
    }
}

const id = 'Fez';
const name = 'Fez';
const sceneDescs: (string | Viewer.SceneDesc)[] = [
    'Levels',
    new FezSceneDesc('levels/abandoned_a', 'abandoned_a'),
    new FezSceneDesc('levels/abandoned_b', 'abandoned_b'),
    new FezSceneDesc('levels/abandoned_c', 'abandoned_c'),
    new FezSceneDesc('levels/ancient_walls', 'ancient_walls'),
    new FezSceneDesc('levels/arch', 'arch'),
    new FezSceneDesc('levels/bell_tower', 'bell_tower'),
    new FezSceneDesc('levels/big_owl', 'big_owl'),
    new FezSceneDesc('levels/big_tower', 'big_tower'),
    new FezSceneDesc('levels/boileroom', 'boileroom'),
    new FezSceneDesc('levels/cabin_interior_a', 'cabin_interior_a'),
    new FezSceneDesc('levels/cabin_interior_b', 'cabin_interior_b'),
    new FezSceneDesc('levels/clock', 'clock'),
    new FezSceneDesc('levels/cmy', 'cmy'),
    new FezSceneDesc('levels/cmy_b', 'cmy_b'),
    new FezSceneDesc('levels/cmy_fork', 'cmy_fork'),
    new FezSceneDesc('levels/code_machine', 'code_machine'),
    new FezSceneDesc('levels/crypt', 'crypt'),
    new FezSceneDesc('levels/drum', 'drum'),
    new FezSceneDesc('levels/elders', 'elders'),
    new FezSceneDesc('levels/extractor_a', 'extractor_a'),
    new FezSceneDesc('levels/five_towers', 'five_towers'),
    new FezSceneDesc('levels/five_towers_cave', 'five_towers_cave'),
    new FezSceneDesc('levels/fox', 'fox'),
    new FezSceneDesc('levels/fractal', 'fractal'),
    new FezSceneDesc('levels/geezer_house', 'geezer_house'),
    new FezSceneDesc('levels/geezer_house_2d', 'geezer_house_2d'),
    new FezSceneDesc('levels/globe', 'globe'),
    new FezSceneDesc('levels/globe_int', 'globe_int'),
    new FezSceneDesc('levels/gomez_house', 'gomez_house'),
    new FezSceneDesc('levels/gomez_house_2d', 'gomez_house_2d'),
    new FezSceneDesc('levels/gomez_house_end_32', 'gomez_house_end_32'),
    new FezSceneDesc('levels/gomez_house_end_64', 'gomez_house_end_64'),
    new FezSceneDesc('levels/grave_cabin', 'grave_cabin'),
    new FezSceneDesc('levels/grave_ghost', 'grave_ghost'),
    new FezSceneDesc('levels/grave_lesser_gate', 'grave_lesser_gate'),
    new FezSceneDesc('levels/grave_treasure_a', 'grave_treasure_a'),
    new FezSceneDesc('levels/graveyard_a', 'graveyard_a'),
    new FezSceneDesc('levels/graveyard_gate', 'graveyard_gate'),
    new FezSceneDesc('levels/hex_rebuild', 'hex_rebuild'),
    new FezSceneDesc('levels/indust_abandoned_a', 'indust_abandoned_a'),
    new FezSceneDesc('levels/industrial_city', 'industrial_city'),
    new FezSceneDesc('levels/industrial_hub', 'industrial_hub'),
    new FezSceneDesc('levels/industrial_superspin', 'industrial_superspin'),
    new FezSceneDesc('levels/kitchen', 'kitchen'),
    new FezSceneDesc('levels/kitchen_2d', 'kitchen_2d'),
    new FezSceneDesc('levels/lava', 'lava'),
    new FezSceneDesc('levels/lava_fork', 'lava_fork'),
    new FezSceneDesc('levels/lava_skull', 'lava_skull'),
    new FezSceneDesc('levels/library_interior', 'library_interior'),
    new FezSceneDesc('levels/lighthouse', 'lighthouse'),
    new FezSceneDesc('levels/lighthouse_house_a', 'lighthouse_house_a'),
    new FezSceneDesc('levels/lighthouse_spin', 'lighthouse_spin'),
    new FezSceneDesc('levels/mausoleum', 'mausoleum'),
    new FezSceneDesc('levels/memory_core', 'memory_core'),
    new FezSceneDesc('levels/mine_a', 'mine_a'),
    new FezSceneDesc('levels/mine_bomb_pillar', 'mine_bomb_pillar'),
    new FezSceneDesc('levels/mine_wrap', 'mine_wrap'),
    new FezSceneDesc('levels/nature_hub', 'nature_hub'),
    new FezSceneDesc('levels/nuzu_abandoned_a', 'nuzu_abandoned_a'),
    new FezSceneDesc('levels/nuzu_abandoned_b', 'nuzu_abandoned_b'),
    new FezSceneDesc('levels/nuzu_boilerroom', 'nuzu_boilerroom'),
    new FezSceneDesc('levels/nuzu_dorm', 'nuzu_dorm'),
    new FezSceneDesc('levels/nuzu_school', 'nuzu_school'),
    new FezSceneDesc('levels/observatory', 'observatory'),
    new FezSceneDesc('levels/octoheahedron', 'octoheahedron'),
    new FezSceneDesc('levels/oldschool', 'oldschool'),
    new FezSceneDesc('levels/oldschool_ruins', 'oldschool_ruins'),
    new FezSceneDesc('levels/orrery', 'orrery'),
    new FezSceneDesc('levels/orrery_b', 'orrery_b'),
    new FezSceneDesc('levels/owl', 'owl'),
    new FezSceneDesc('levels/parlor', 'parlor'),
    new FezSceneDesc('levels/parlor_2d', 'parlor_2d'),
    new FezSceneDesc('levels/pivot_one', 'pivot_one'),
    new FezSceneDesc('levels/pivot_two', 'pivot_two'),
    new FezSceneDesc('levels/pivot_three', 'pivot_three'),
    new FezSceneDesc('levels/pivot_three_cave', 'pivot_three_cave'),
    new FezSceneDesc('levels/pivot_watertower', 'pivot_watertower'),
    new FezSceneDesc('levels/purple_lodge', 'purple_lodge'),
    new FezSceneDesc('levels/purple_lodge_ruin', 'purple_lodge_ruin'),
    new FezSceneDesc('levels/pyramid', 'pyramid'),
    new FezSceneDesc('levels/quantum', 'quantum'),
    new FezSceneDesc('levels/rails', 'rails'),
    new FezSceneDesc('levels/ritual', 'ritual'),
    new FezSceneDesc('levels/school', 'school'),
    new FezSceneDesc('levels/school_2d', 'school_2d'),
    new FezSceneDesc('levels/sewer_fork', 'sewer_fork'),
    new FezSceneDesc('levels/sewer_geyser', 'sewer_geyser'),
    new FezSceneDesc('levels/sewer_hub', 'sewer_hub'),
    new FezSceneDesc('levels/sewer_lesser_gate_b', 'sewer_lesser_gate_b'),
    new FezSceneDesc('levels/sewer_pillars', 'sewer_pillars'),
    new FezSceneDesc('levels/sewer_pivot', 'sewer_pivot'),
    new FezSceneDesc('levels/sewer_qr', 'sewer_qr'),
    new FezSceneDesc('levels/sewer_start', 'sewer_start'),
    new FezSceneDesc('levels/sewer_to_lava', 'sewer_to_lava'),
    new FezSceneDesc('levels/sewer_treasure_one', 'sewer_treasure_one'),
    new FezSceneDesc('levels/sewer_treasure_two', 'sewer_treasure_two'),
    new FezSceneDesc('levels/showers', 'showers'),
    new FezSceneDesc('levels/skull', 'skull'),
    new FezSceneDesc('levels/skull_b', 'skull_b'),
    new FezSceneDesc('levels/spinning_plates', 'spinning_plates'),
    new FezSceneDesc('levels/stargate', 'stargate'),
    new FezSceneDesc('levels/stargate_ruins', 'stargate_ruins'),
    new FezSceneDesc('levels/superspin_cave', 'superspin_cave'),
    new FezSceneDesc('levels/telescope', 'telescope'),
    new FezSceneDesc('levels/temple_of_love', 'temple_of_love'),
    new FezSceneDesc('levels/throne', 'throne'),
    new FezSceneDesc('levels/tree', 'tree'),
    new FezSceneDesc('levels/tree_crumble', 'tree_crumble'),
    new FezSceneDesc('levels/tree_of_death', 'tree_of_death'),
    new FezSceneDesc('levels/tree_roots', 'tree_roots'),
    new FezSceneDesc('levels/tree_sky', 'tree_sky'),
    new FezSceneDesc('levels/triple_pivot_cave', 'triple_pivot_cave'),
    new FezSceneDesc('levels/two_walls', 'two_walls'),
    new FezSceneDesc('levels/villageville_2d', 'villageville_2d'),
    new FezSceneDesc('levels/villageville_3d', 'villageville_3d'),
    new FezSceneDesc('levels/villageville_3d_end_32', 'villageville_3d_end_32'),
    new FezSceneDesc('levels/villageville_3d_end_64', 'villageville_3d_end_64'),
    new FezSceneDesc('levels/visitor', 'visitor'),
    new FezSceneDesc('levels/wall_hole', 'wall_hole'),
    new FezSceneDesc('levels/wall_interior_a', 'wall_interior_a'),
    new FezSceneDesc('levels/wall_interior_b', 'wall_interior_b'),
    new FezSceneDesc('levels/wall_interior_hole', 'wall_interior_hole'),
    new FezSceneDesc('levels/wall_kitchen', 'wall_kitchen'),
    new FezSceneDesc('levels/wall_school', 'wall_school'),
    new FezSceneDesc('levels/wall_village', 'wall_village'),
    new FezSceneDesc('levels/water_pyramid', 'water_pyramid'),
    new FezSceneDesc('levels/water_tower', 'water_tower'),
    new FezSceneDesc('levels/water_wheel', 'water_wheel'),
    new FezSceneDesc('levels/water_wheel_b', 'water_wheel_b'),
    new FezSceneDesc('levels/waterfall', 'waterfall'),
    new FezSceneDesc('levels/waterfall_alt', 'waterfall_alt'),
    new FezSceneDesc('levels/watertower_secret', 'watertower_secret'),
    new FezSceneDesc('levels/weightswitch_temple', 'weightswitch_temple'),
    new FezSceneDesc('levels/well_2', 'well_2'),
    new FezSceneDesc('levels/windmill_cave', 'windmill_cave'),
    new FezSceneDesc('levels/windmill_int', 'windmill_int'),
    new FezSceneDesc('levels/zu_4_side', 'zu_4_side'),
    new FezSceneDesc('levels/zu_bridge', 'zu_bridge'),
    new FezSceneDesc('levels/zu_city', 'zu_city'),
    new FezSceneDesc('levels/zu_city_ruins', 'zu_city_ruins'),
    new FezSceneDesc('levels/zu_code_loop', 'zu_code_loop'),
    new FezSceneDesc('levels/zu_fork', 'zu_fork'),
    new FezSceneDesc('levels/zu_heads', 'zu_heads'),
    new FezSceneDesc('levels/zu_house_empty', 'zu_house_empty'),
    new FezSceneDesc('levels/zu_house_empty_b', 'zu_house_empty_b'),
    new FezSceneDesc('levels/zu_house_qr', 'zu_house_qr'),
    new FezSceneDesc('levels/zu_house_ruin_gate', 'zu_house_ruin_gate'),
    new FezSceneDesc('levels/zu_house_ruin_visitors', 'zu_house_ruin_visitors'),
    new FezSceneDesc('levels/zu_house_scaffolding', 'zu_house_scaffolding'),
    new FezSceneDesc('levels/zu_library', 'zu_library'),
    new FezSceneDesc('levels/zu_switch', 'zu_switch'),
    new FezSceneDesc('levels/zu_switch_b', 'zu_switch_b'),
    new FezSceneDesc('levels/zu_tetris', 'zu_tetris'),
    new FezSceneDesc('levels/zu_throne_ruins', 'zu_throne_ruins'),
    new FezSceneDesc('levels/zu_unfold', 'zu_unfold'),
    new FezSceneDesc('levels/zu_zuish', 'zu_zuish'),
    'Art Objects',
    new FezArtObjectSceneDesc('art_objects/1_bit_doorao', '1_bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/16_bit_doorao', '16_bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/2_bit_doorao', '2_bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/3-bit_doorao', '3-bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/32_bit_door_brokenao', '32_bit_door_brokenao'),
    new FezArtObjectSceneDesc('art_objects/32_bit_doorao', '32_bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/4_bit_doorao', '4_bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/4_side_blockao', '4_side_blockao'),
    new FezArtObjectSceneDesc('art_objects/64_bit_doorao', '64_bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/8bit_doorao', '8bit_doorao'),
    new FezArtObjectSceneDesc('art_objects/bell_hookao', 'bell_hookao'),
    new FezArtObjectSceneDesc('art_objects/bellao', 'bellao'),
    new FezArtObjectSceneDesc('art_objects/big_owl_headao', 'big_owl_headao'),
    new FezArtObjectSceneDesc('art_objects/big_owl_pyramid_headao', 'big_owl_pyramid_headao'),
    new FezArtObjectSceneDesc('art_objects/big_owl_pyramidao', 'big_owl_pyramidao'),
    new FezArtObjectSceneDesc('art_objects/big_owlao', 'big_owlao'),
    new FezArtObjectSceneDesc('art_objects/big_spinao', 'big_spinao'),
    new FezArtObjectSceneDesc('art_objects/big_stone_doorao', 'big_stone_doorao'),
    new FezArtObjectSceneDesc('art_objects/big_telescopeao', 'big_telescopeao'),
    new FezArtObjectSceneDesc('art_objects/big_tombstone_baseao', 'big_tombstone_baseao'),
    new FezArtObjectSceneDesc('art_objects/big_tombstoneao', 'big_tombstoneao'),
    new FezArtObjectSceneDesc('art_objects/big_tree_orangeao', 'big_tree_orangeao'),
    new FezArtObjectSceneDesc('art_objects/big_tree_pinkao', 'big_tree_pinkao'),
    new FezArtObjectSceneDesc('art_objects/big_treeao', 'big_treeao'),
    new FezArtObjectSceneDesc('art_objects/big_water_tankao', 'big_water_tankao'),
    new FezArtObjectSceneDesc('art_objects/big_windmillao', 'big_windmillao'),
    new FezArtObjectSceneDesc('art_objects/birdcage_aao', 'birdcage_aao'),
    new FezArtObjectSceneDesc('art_objects/bookshelf_bigao', 'bookshelf_bigao'),
    new FezArtObjectSceneDesc('art_objects/bookshelfao', 'bookshelfao'),
    new FezArtObjectSceneDesc('art_objects/bookthingao', 'bookthingao'),
    new FezArtObjectSceneDesc('art_objects/bunkbedsao', 'bunkbedsao'),
    new FezArtObjectSceneDesc('art_objects/cameraao', 'cameraao'),
    new FezArtObjectSceneDesc('art_objects/candles_aao', 'candles_aao'),
    new FezArtObjectSceneDesc('art_objects/candles_bao', 'candles_bao'),
    new FezArtObjectSceneDesc('art_objects/candles_cao', 'candles_cao'),
    new FezArtObjectSceneDesc('art_objects/clock_baseao', 'clock_baseao'),
    new FezArtObjectSceneDesc('art_objects/clock_boltao', 'clock_boltao'),
    new FezArtObjectSceneDesc('art_objects/clock_cubeao', 'clock_cubeao'),
    new FezArtObjectSceneDesc('art_objects/clock_topao', 'clock_topao'),
    new FezArtObjectSceneDesc('art_objects/clockcoreao', 'clockcoreao'),
    new FezArtObjectSceneDesc('art_objects/clockfaceao', 'clockfaceao'),
    new FezArtObjectSceneDesc('art_objects/clockhand_bao', 'clockhand_bao'),
    new FezArtObjectSceneDesc('art_objects/clockhand_gao', 'clockhand_gao'),
    new FezArtObjectSceneDesc('art_objects/clockhand_rao', 'clockhand_rao'),
    new FezArtObjectSceneDesc('art_objects/clockhand_wao', 'clockhand_wao'),
    new FezArtObjectSceneDesc('art_objects/cmy_crystal_cao', 'cmy_crystal_cao'),
    new FezArtObjectSceneDesc('art_objects/cmy_crystal_kao', 'cmy_crystal_kao'),
    new FezArtObjectSceneDesc('art_objects/cmy_crystal_mao', 'cmy_crystal_mao'),
    new FezArtObjectSceneDesc('art_objects/cmy_crystal_yao', 'cmy_crystal_yao'),
    new FezArtObjectSceneDesc('art_objects/cmy_doorao', 'cmy_doorao'),
    new FezArtObjectSceneDesc('art_objects/cmy_head_aao', 'cmy_head_aao'),
    new FezArtObjectSceneDesc('art_objects/cmy_head_bao', 'cmy_head_bao'),
    new FezArtObjectSceneDesc('art_objects/cmy_monolithao', 'cmy_monolithao'),
    new FezArtObjectSceneDesc('art_objects/cmy_postao', 'cmy_postao'),
    new FezArtObjectSceneDesc('art_objects/cmy_zuhead_lao', 'cmy_zuhead_lao'),
    new FezArtObjectSceneDesc('art_objects/cmy_zuhead_sao', 'cmy_zuhead_sao'),
    new FezArtObjectSceneDesc('art_objects/cmyk_doorao', 'cmyk_doorao'),
    new FezArtObjectSceneDesc('art_objects/code_machine_aao', 'code_machine_aao'),
    new FezArtObjectSceneDesc('art_objects/code_monolith_codemachineao', 'code_monolith_codemachineao'),
    new FezArtObjectSceneDesc('art_objects/code_monolith_waterfallao', 'code_monolith_waterfallao'),
    new FezArtObjectSceneDesc('art_objects/crossao', 'crossao'),
    new FezArtObjectSceneDesc('art_objects/crownao', 'crownao'),
    new FezArtObjectSceneDesc('art_objects/cube_pillarao', 'cube_pillarao'),
    new FezArtObjectSceneDesc('art_objects/cube_tree_d_pinkao', 'cube_tree_d_pinkao'),
    new FezArtObjectSceneDesc('art_objects/cube_tree_dao', 'cube_tree_dao'),
    new FezArtObjectSceneDesc('art_objects/cube_tree_orangeao', 'cube_tree_orangeao'),
    new FezArtObjectSceneDesc('art_objects/deathskull_aao', 'deathskull_aao'),
    new FezArtObjectSceneDesc('art_objects/deathskull_bao', 'deathskull_bao'),
    new FezArtObjectSceneDesc('art_objects/downgrowth_aao', 'downgrowth_aao'),
    new FezArtObjectSceneDesc('art_objects/downgrowth_bao', 'downgrowth_bao'),
    new FezArtObjectSceneDesc('art_objects/evol_pillar2222ao', 'evol_pillar2222ao'),
    new FezArtObjectSceneDesc('art_objects/exit_pillarao', 'exit_pillarao'),
    new FezArtObjectSceneDesc('art_objects/extractorao', 'extractorao'),
    new FezArtObjectSceneDesc('art_objects/fake_bender_lao', 'fake_bender_lao'),
    new FezArtObjectSceneDesc('art_objects/fake_emitter_lao', 'fake_emitter_lao'),
    new FezArtObjectSceneDesc('art_objects/fake_emitter_tao', 'fake_emitter_tao'),
    new FezArtObjectSceneDesc('art_objects/fake_timeswitch_movingpartao', 'fake_timeswitch_movingpartao'),
    new FezArtObjectSceneDesc('art_objects/fake_timeswitchao', 'fake_timeswitchao'),
    new FezArtObjectSceneDesc('art_objects/fez_signao', 'fez_signao'),
    new FezArtObjectSceneDesc('art_objects/fifty_signao', 'fifty_signao'),
    new FezArtObjectSceneDesc('art_objects/food_counter_aao', 'food_counter_aao'),
    new FezArtObjectSceneDesc('art_objects/food_stuff_0ao', 'food_stuff_0ao'),
    new FezArtObjectSceneDesc('art_objects/food_stuff_1ao', 'food_stuff_1ao'),
    new FezArtObjectSceneDesc('art_objects/food_stuff_2ao', 'food_stuff_2ao'),
    new FezArtObjectSceneDesc('art_objects/food_stuff_3ao', 'food_stuff_3ao'),
    new FezArtObjectSceneDesc('art_objects/fork_blueao', 'fork_blueao'),
    new FezArtObjectSceneDesc('art_objects/fork_greenao', 'fork_greenao'),
    new FezArtObjectSceneDesc('art_objects/fork_redao', 'fork_redao'),
    new FezArtObjectSceneDesc('art_objects/forkao', 'forkao'),
    new FezArtObjectSceneDesc('art_objects/fps_post_pao', 'fps_post_pao'),
    new FezArtObjectSceneDesc('art_objects/fps_post_wao', 'fps_post_wao'),
    new FezArtObjectSceneDesc('art_objects/fractal_cubeao', 'fractal_cubeao'),
    new FezArtObjectSceneDesc('art_objects/fractal_globe_baseao', 'fractal_globe_baseao'),
    new FezArtObjectSceneDesc('art_objects/fractal_globe_topao', 'fractal_globe_topao'),
    new FezArtObjectSceneDesc('art_objects/fractal_globeao', 'fractal_globeao'),
    new FezArtObjectSceneDesc('art_objects/gargoyle_aao', 'gargoyle_aao'),
    new FezArtObjectSceneDesc('art_objects/gate_brokenao', 'gate_brokenao'),
    new FezArtObjectSceneDesc('art_objects/gate_graveao', 'gate_graveao'),
    new FezArtObjectSceneDesc('art_objects/gate_industrialao', 'gate_industrialao'),
    new FezArtObjectSceneDesc('art_objects/gate_sewerao', 'gate_sewerao'),
    new FezArtObjectSceneDesc('art_objects/gateao', 'gateao'),
    new FezArtObjectSceneDesc('art_objects/gen_1ao', 'gen_1ao'),
    new FezArtObjectSceneDesc('art_objects/gen_2ao', 'gen_2ao'),
    new FezArtObjectSceneDesc('art_objects/gen_3ao', 'gen_3ao'),
    new FezArtObjectSceneDesc('art_objects/gen_4ao', 'gen_4ao'),
    new FezArtObjectSceneDesc('art_objects/gen_baseao', 'gen_baseao'),
    new FezArtObjectSceneDesc('art_objects/gen_capao', 'gen_capao'),
    new FezArtObjectSceneDesc('art_objects/gen_doorframeao', 'gen_doorframeao'),
    new FezArtObjectSceneDesc('art_objects/giant_skullao', 'giant_skullao'),
    new FezArtObjectSceneDesc('art_objects/giant_tree_pinkao', 'giant_tree_pinkao'),
    new FezArtObjectSceneDesc('art_objects/giant_treeao', 'giant_treeao'),
    new FezArtObjectSceneDesc('art_objects/globe_arcao', 'globe_arcao'),
    new FezArtObjectSceneDesc('art_objects/globe_arch_bao', 'globe_arch_bao'),
    new FezArtObjectSceneDesc('art_objects/globe_pillarao', 'globe_pillarao'),
    new FezArtObjectSceneDesc('art_objects/globe_pivotao', 'globe_pivotao'),
    new FezArtObjectSceneDesc('art_objects/globe_topao', 'globe_topao'),
    new FezArtObjectSceneDesc('art_objects/globeao', 'globeao'),
    new FezArtObjectSceneDesc('art_objects/grave_alcove_bao', 'grave_alcove_bao'),
    new FezArtObjectSceneDesc('art_objects/grave_alcoveao', 'grave_alcoveao'),
    new FezArtObjectSceneDesc('art_objects/grave_alcoveao_b', 'grave_alcoveao_b'),
    new FezArtObjectSceneDesc('art_objects/grave_cabin_natureao', 'grave_cabin_natureao'),
    new FezArtObjectSceneDesc('art_objects/grave_cabinao', 'grave_cabinao'),
    new FezArtObjectSceneDesc('art_objects/grave_cubeao', 'grave_cubeao'),
    new FezArtObjectSceneDesc('art_objects/grave_entranceao', 'grave_entranceao'),
    new FezArtObjectSceneDesc('art_objects/grave_gateao', 'grave_gateao'),
    new FezArtObjectSceneDesc('art_objects/grave_pillarao', 'grave_pillarao'),
    new FezArtObjectSceneDesc('art_objects/greenboardao', 'greenboardao'),
    new FezArtObjectSceneDesc('art_objects/hex_baseao', 'hex_baseao'),
    new FezArtObjectSceneDesc('art_objects/hex_pillar_aao', 'hex_pillar_aao'),
    new FezArtObjectSceneDesc('art_objects/hex_trigger_aao', 'hex_trigger_aao'),
    new FezArtObjectSceneDesc('art_objects/hex_trigger_glowao', 'hex_trigger_glowao'),
    new FezArtObjectSceneDesc('art_objects/hexahedron_1ao', 'hexahedron_1ao'),
    new FezArtObjectSceneDesc('art_objects/hexahedron_monolithao', 'hexahedron_monolithao'),
    new FezArtObjectSceneDesc('art_objects/hubdoors_bao', 'hubdoors_bao'),
    new FezArtObjectSceneDesc('art_objects/hubdoorsao', 'hubdoorsao'),
    new FezArtObjectSceneDesc('art_objects/huge_tree_orangeao', 'huge_tree_orangeao'),
    new FezArtObjectSceneDesc('art_objects/huge_tree_pinkao', 'huge_tree_pinkao'),
    new FezArtObjectSceneDesc('art_objects/huge_treeao', 'huge_treeao'),
    new FezArtObjectSceneDesc('art_objects/indust_big_door_frameao', 'indust_big_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/indust_big_doorao', 'indust_big_doorao'),
    new FezArtObjectSceneDesc('art_objects/indust_cave_metal_doorao', 'indust_cave_metal_doorao'),
    new FezArtObjectSceneDesc('art_objects/indust_cave_stone_doorao', 'indust_cave_stone_doorao'),
    new FezArtObjectSceneDesc('art_objects/indust_core_colorsao', 'indust_core_colorsao'),
    new FezArtObjectSceneDesc('art_objects/indust_core_spinao', 'indust_core_spinao'),
    new FezArtObjectSceneDesc('art_objects/indust_core_topao', 'indust_core_topao'),
    new FezArtObjectSceneDesc('art_objects/indust_doorframe_aao', 'indust_doorframe_aao'),
    new FezArtObjectSceneDesc('art_objects/indust_doorframe_bao', 'indust_doorframe_bao'),
    new FezArtObjectSceneDesc('art_objects/industrial_door_frameao', 'industrial_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/industrial_girders_support_doubleao', 'industrial_girders_support_doubleao'),
    new FezArtObjectSceneDesc('art_objects/industrial_girders_support_singleao', 'industrial_girders_support_singleao'),
    new FezArtObjectSceneDesc('art_objects/int_base_drumao', 'int_base_drumao'),
    new FezArtObjectSceneDesc('art_objects/int_bed_aao', 'int_bed_aao'),
    new FezArtObjectSceneDesc('art_objects/int_boiler_nuzuao', 'int_boiler_nuzuao'),
    new FezArtObjectSceneDesc('art_objects/int_boiler_pipe_nuzuao', 'int_boiler_pipe_nuzuao'),
    new FezArtObjectSceneDesc('art_objects/int_boiler_pipeao', 'int_boiler_pipeao'),
    new FezArtObjectSceneDesc('art_objects/int_boiler_table_nuzuao', 'int_boiler_table_nuzuao'),
    new FezArtObjectSceneDesc('art_objects/int_boiler_tableao', 'int_boiler_tableao'),
    new FezArtObjectSceneDesc('art_objects/int_boilerao', 'int_boilerao'),
    new FezArtObjectSceneDesc('art_objects/int_ceiling_lamp_0ao', 'int_ceiling_lamp_0ao'),
    new FezArtObjectSceneDesc('art_objects/int_ceiling_lamp_1ao', 'int_ceiling_lamp_1ao'),
    new FezArtObjectSceneDesc('art_objects/int_chairao', 'int_chairao'),
    new FezArtObjectSceneDesc('art_objects/int_crashao', 'int_crashao'),
    new FezArtObjectSceneDesc('art_objects/int_fireplace_dao', 'int_fireplace_dao'),
    new FezArtObjectSceneDesc('art_objects/int_fireplaceao', 'int_fireplaceao'),
    new FezArtObjectSceneDesc('art_objects/int_floor_tomao', 'int_floor_tomao'),
    new FezArtObjectSceneDesc('art_objects/int_fridgeao', 'int_fridgeao'),
    new FezArtObjectSceneDesc('art_objects/int_grandfatherao', 'int_grandfatherao'),
    new FezArtObjectSceneDesc('art_objects/int_hihatao', 'int_hihatao'),
    new FezArtObjectSceneDesc('art_objects/int_kitchen_stuff0ao', 'int_kitchen_stuff0ao'),
    new FezArtObjectSceneDesc('art_objects/int_kitchen_stuff1ao', 'int_kitchen_stuff1ao'),
    new FezArtObjectSceneDesc('art_objects/int_kitchen_stuff2ao', 'int_kitchen_stuff2ao'),
    new FezArtObjectSceneDesc('art_objects/int_kitchen_stuff3ao', 'int_kitchen_stuff3ao'),
    new FezArtObjectSceneDesc('art_objects/int_metal_tableao', 'int_metal_tableao'),
    new FezArtObjectSceneDesc('art_objects/int_mini_treeao', 'int_mini_treeao'),
    new FezArtObjectSceneDesc('art_objects/int_mop_bucketao', 'int_mop_bucketao'),
    new FezArtObjectSceneDesc('art_objects/int_mugao', 'int_mugao'),
    new FezArtObjectSceneDesc('art_objects/int_ovenao', 'int_ovenao'),
    new FezArtObjectSceneDesc('art_objects/int_parlor_books_aao', 'int_parlor_books_aao'),
    new FezArtObjectSceneDesc('art_objects/int_parlor_booksao', 'int_parlor_booksao'),
    new FezArtObjectSceneDesc('art_objects/int_parlor_chairao', 'int_parlor_chairao'),
    new FezArtObjectSceneDesc('art_objects/int_parlor_passageao', 'int_parlor_passageao'),
    new FezArtObjectSceneDesc('art_objects/int_parlor_poufao', 'int_parlor_poufao'),
    new FezArtObjectSceneDesc('art_objects/int_potsao', 'int_potsao'),
    new FezArtObjectSceneDesc('art_objects/int_shelfao', 'int_shelfao'),
    new FezArtObjectSceneDesc('art_objects/int_sinkao', 'int_sinkao'),
    new FezArtObjectSceneDesc('art_objects/int_snareao', 'int_snareao'),
    new FezArtObjectSceneDesc('art_objects/int_stoolao', 'int_stoolao'),
    new FezArtObjectSceneDesc('art_objects/int_table_aao', 'int_table_aao'),
    new FezArtObjectSceneDesc('art_objects/int_tomsao', 'int_tomsao'),
    new FezArtObjectSceneDesc('art_objects/jack_caseao', 'jack_caseao'),
    new FezArtObjectSceneDesc('art_objects/jack_springao', 'jack_springao'),
    new FezArtObjectSceneDesc('art_objects/lava_big_frameao', 'lava_big_frameao'),
    new FezArtObjectSceneDesc('art_objects/lava_skullao', 'lava_skullao'),
    new FezArtObjectSceneDesc('art_objects/lava_spin_1x1ao', 'lava_spin_1x1ao'),
    new FezArtObjectSceneDesc('art_objects/lava_spin_2x1ao', 'lava_spin_2x1ao'),
    new FezArtObjectSceneDesc('art_objects/lava_spin_2x2ao', 'lava_spin_2x2ao'),
    new FezArtObjectSceneDesc('art_objects/lava_spin_2x2bao', 'lava_spin_2x2bao'),
    new FezArtObjectSceneDesc('art_objects/lava_spin_3x1ao', 'lava_spin_3x1ao'),
    new FezArtObjectSceneDesc('art_objects/lava_stone_door_frameao', 'lava_stone_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/lava_valveao', 'lava_valveao'),
    new FezArtObjectSceneDesc('art_objects/ledge_aao', 'ledge_aao'),
    new FezArtObjectSceneDesc('art_objects/ledge_bao', 'ledge_bao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate__base_industao', 'lesser_gate__base_industao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_base_cmyao', 'lesser_gate_base_cmyao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_base_graveao', 'lesser_gate_base_graveao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_base_lavaao', 'lesser_gate_base_lavaao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_base_mineao', 'lesser_gate_base_mineao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_baseao', 'lesser_gate_baseao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_cmyao', 'lesser_gate_cmyao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_graveao', 'lesser_gate_graveao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_industao', 'lesser_gate_industao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_lavaao', 'lesser_gate_lavaao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_mineao', 'lesser_gate_mineao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gate_zuao', 'lesser_gate_zuao'),
    new FezArtObjectSceneDesc('art_objects/lesser_gateao', 'lesser_gateao'),
    new FezArtObjectSceneDesc('art_objects/letter_cubeao', 'letter_cubeao'),
    new FezArtObjectSceneDesc('art_objects/lib_int_doorao', 'lib_int_doorao'),
    new FezArtObjectSceneDesc('art_objects/lib_int_pillarao', 'lib_int_pillarao'),
    new FezArtObjectSceneDesc('art_objects/lib_stone_pillarao', 'lib_stone_pillarao'),
    new FezArtObjectSceneDesc('art_objects/library_coreao', 'library_coreao'),
    new FezArtObjectSceneDesc('art_objects/library_deskao', 'library_deskao'),
    new FezArtObjectSceneDesc('art_objects/library_doorao', 'library_doorao'),
    new FezArtObjectSceneDesc('art_objects/library_fireplaceao', 'library_fireplaceao'),
    new FezArtObjectSceneDesc('art_objects/library_pillar_aao', 'library_pillar_aao'),
    new FezArtObjectSceneDesc('art_objects/library_pillarao', 'library_pillarao'),
    new FezArtObjectSceneDesc('art_objects/library_pyramidao', 'library_pyramidao'),
    new FezArtObjectSceneDesc('art_objects/library_roofao', 'library_roofao'),
    new FezArtObjectSceneDesc('art_objects/lifesaverao', 'lifesaverao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_aao', 'lighthouse_aao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_coreao', 'lighthouse_coreao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_int_doorao', 'lighthouse_int_doorao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_platform_aao', 'lighthouse_platform_aao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_spin_aao', 'lighthouse_spin_aao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_testao', 'lighthouse_testao'),
    new FezArtObjectSceneDesc('art_objects/lighthouse_topao', 'lighthouse_topao'),
    new FezArtObjectSceneDesc('art_objects/locker_benchao', 'locker_benchao'),
    new FezArtObjectSceneDesc('art_objects/lockerao', 'lockerao'),
    new FezArtObjectSceneDesc('art_objects/marker_fourao', 'marker_fourao'),
    new FezArtObjectSceneDesc('art_objects/marker_oneao', 'marker_oneao'),
    new FezArtObjectSceneDesc('art_objects/marker_threeao', 'marker_threeao'),
    new FezArtObjectSceneDesc('art_objects/marker_twoao', 'marker_twoao'),
    new FezArtObjectSceneDesc('art_objects/math_doorao', 'math_doorao'),
    new FezArtObjectSceneDesc('art_objects/mausoleum_cryptao', 'mausoleum_cryptao'),
    new FezArtObjectSceneDesc('art_objects/mausoleum_pillars_cryptao', 'mausoleum_pillars_cryptao'),
    new FezArtObjectSceneDesc('art_objects/mausoleum_pillarsao', 'mausoleum_pillarsao'),
    new FezArtObjectSceneDesc('art_objects/mausoleumao', 'mausoleumao'),
    new FezArtObjectSceneDesc('art_objects/mech_5x5ao', 'mech_5x5ao'),
    new FezArtObjectSceneDesc('art_objects/mech_support_aao', 'mech_support_aao'),
    new FezArtObjectSceneDesc('art_objects/megalithao', 'megalithao'),
    new FezArtObjectSceneDesc('art_objects/memory_core_signageao', 'memory_core_signageao'),
    new FezArtObjectSceneDesc('art_objects/menu_cube_cmy', 'menu_cube_cmy'),
    new FezArtObjectSceneDesc('art_objects/menu_cube_gb', 'menu_cube_gb'),
    new FezArtObjectSceneDesc('art_objects/menu_cube_virtual', 'menu_cube_virtual'),
    new FezArtObjectSceneDesc('art_objects/menu_cubeao', 'menu_cubeao'),
    new FezArtObjectSceneDesc('art_objects/mine_big_crateao', 'mine_big_crateao'),
    new FezArtObjectSceneDesc('art_objects/mine_city_big_doorao', 'mine_city_big_doorao'),
    new FezArtObjectSceneDesc('art_objects/mine_city_door_baseao', 'mine_city_door_baseao'),
    new FezArtObjectSceneDesc('art_objects/mine_city_door_tubeao', 'mine_city_door_tubeao'),
    new FezArtObjectSceneDesc('art_objects/mine_doorao', 'mine_doorao'),
    new FezArtObjectSceneDesc('art_objects/mine_entrance_aao', 'mine_entrance_aao'),
    new FezArtObjectSceneDesc('art_objects/mine_entrance_bao', 'mine_entrance_bao'),
    new FezArtObjectSceneDesc('art_objects/mine_entrance_cao', 'mine_entrance_cao'),
    new FezArtObjectSceneDesc('art_objects/mine_tools_0ao', 'mine_tools_0ao'),
    new FezArtObjectSceneDesc('art_objects/mine_tools_1ao', 'mine_tools_1ao'),
    new FezArtObjectSceneDesc('art_objects/mine_tools_2ao', 'mine_tools_2ao'),
    new FezArtObjectSceneDesc('art_objects/minecart_aao', 'minecart_aao'),
    new FezArtObjectSceneDesc('art_objects/monolithao', 'monolithao'),
    new FezArtObjectSceneDesc('art_objects/moss_aao', 'moss_aao'),
    new FezArtObjectSceneDesc('art_objects/mothercubeao', 'mothercubeao'),
    new FezArtObjectSceneDesc('art_objects/neon_cablesao', 'neon_cablesao'),
    new FezArtObjectSceneDesc('art_objects/neon_foodao', 'neon_foodao'),
    new FezArtObjectSceneDesc('art_objects/neon_frame_aao', 'neon_frame_aao'),
    new FezArtObjectSceneDesc('art_objects/neon_frame_bao', 'neon_frame_bao'),
    new FezArtObjectSceneDesc('art_objects/neon_frame_cao', 'neon_frame_cao'),
    new FezArtObjectSceneDesc('art_objects/neon_frame_dao', 'neon_frame_dao'),
    new FezArtObjectSceneDesc('art_objects/neon_goodao', 'neon_goodao'),
    new FezArtObjectSceneDesc('art_objects/neon_hardao', 'neon_hardao'),
    new FezArtObjectSceneDesc('art_objects/neon_nuao', 'neon_nuao'),
    new FezArtObjectSceneDesc('art_objects/neon_supportao', 'neon_supportao'),
    new FezArtObjectSceneDesc('art_objects/neon_workao', 'neon_workao'),
    new FezArtObjectSceneDesc('art_objects/neon_zuao', 'neon_zuao'),
    new FezArtObjectSceneDesc('art_objects/new_hexao', 'new_hexao'),
    new FezArtObjectSceneDesc('art_objects/new_minecartao', 'new_minecartao'),
    new FezArtObjectSceneDesc('art_objects/newhouse_aao', 'newhouse_aao'),
    new FezArtObjectSceneDesc('art_objects/newhouse_bao', 'newhouse_bao'),
    new FezArtObjectSceneDesc('art_objects/newshroomao', 'newshroomao'),
    new FezArtObjectSceneDesc('art_objects/number_cubeao', 'number_cubeao'),
    new FezArtObjectSceneDesc('art_objects/nutao', 'nutao'),
    new FezArtObjectSceneDesc('art_objects/nutbolt_base_underao', 'nutbolt_base_underao'),
    new FezArtObjectSceneDesc('art_objects/nutbolt_baseao', 'nutbolt_baseao'),
    new FezArtObjectSceneDesc('art_objects/nutbolt_cap_bao', 'nutbolt_cap_bao'),
    new FezArtObjectSceneDesc('art_objects/nutbolt_capao', 'nutbolt_capao'),
    new FezArtObjectSceneDesc('art_objects/nuzu_benchao', 'nuzu_benchao'),
    new FezArtObjectSceneDesc('art_objects/nuzu_big_doorao', 'nuzu_big_doorao'),
    new FezArtObjectSceneDesc('art_objects/nuzu_sewer_barsao', 'nuzu_sewer_barsao'),
    new FezArtObjectSceneDesc('art_objects/nuzu_signao', 'nuzu_signao'),
    new FezArtObjectSceneDesc('art_objects/nuzu_watertowerao', 'nuzu_watertowerao'),
    new FezArtObjectSceneDesc('art_objects/obs_dome_aao', 'obs_dome_aao'),
    new FezArtObjectSceneDesc('art_objects/obs_dome_bao', 'obs_dome_bao'),
    new FezArtObjectSceneDesc('art_objects/obs_dome_cao', 'obs_dome_cao'),
    new FezArtObjectSceneDesc('art_objects/obs_dome_dao', 'obs_dome_dao'),
    new FezArtObjectSceneDesc('art_objects/observatory_doorframeao', 'observatory_doorframeao'),
    new FezArtObjectSceneDesc('art_objects/oldschool_desk_grassao', 'oldschool_desk_grassao'),
    new FezArtObjectSceneDesc('art_objects/oldschool_deskao', 'oldschool_deskao'),
    new FezArtObjectSceneDesc('art_objects/orange_piston_shaftao', 'orange_piston_shaftao'),
    new FezArtObjectSceneDesc('art_objects/orange_pistonao', 'orange_pistonao'),
    new FezArtObjectSceneDesc('art_objects/orr_cog_lao', 'orr_cog_lao'),
    new FezArtObjectSceneDesc('art_objects/orr_cog_mao', 'orr_cog_mao'),
    new FezArtObjectSceneDesc('art_objects/orr_cog_sao', 'orr_cog_sao'),
    new FezArtObjectSceneDesc('art_objects/orr_earth_branchao', 'orr_earth_branchao'),
    new FezArtObjectSceneDesc('art_objects/orr_earthao', 'orr_earthao'),
    new FezArtObjectSceneDesc('art_objects/orr_moon_branchao', 'orr_moon_branchao'),
    new FezArtObjectSceneDesc('art_objects/orr_moonao', 'orr_moonao'),
    new FezArtObjectSceneDesc('art_objects/orr_planet_wao', 'orr_planet_wao'),
    new FezArtObjectSceneDesc('art_objects/orr_sun_branchao', 'orr_sun_branchao'),
    new FezArtObjectSceneDesc('art_objects/orr_sunao', 'orr_sunao'),
    new FezArtObjectSceneDesc('art_objects/orr_w_branchao', 'orr_w_branchao'),
    new FezArtObjectSceneDesc('art_objects/owl_base_fillerao', 'owl_base_fillerao'),
    new FezArtObjectSceneDesc('art_objects/owl_baseao', 'owl_baseao'),
    new FezArtObjectSceneDesc('art_objects/owl_statue_body_ao', 'owl_statue_body_ao'),
    new FezArtObjectSceneDesc('art_objects/owl_statue_drapes_bao', 'owl_statue_drapes_bao'),
    new FezArtObjectSceneDesc('art_objects/owl_statue_drapesao', 'owl_statue_drapesao'),
    new FezArtObjectSceneDesc('art_objects/owl_statue_headao', 'owl_statue_headao'),
    new FezArtObjectSceneDesc('art_objects/owl_statueao', 'owl_statueao'),
    new FezArtObjectSceneDesc('art_objects/piston_big_baseao', 'piston_big_baseao'),
    new FezArtObjectSceneDesc('art_objects/piston_bigao', 'piston_bigao'),
    new FezArtObjectSceneDesc('art_objects/pivot_base_ind_caveao', 'pivot_base_ind_caveao'),
    new FezArtObjectSceneDesc('art_objects/pivot_base_redao', 'pivot_base_redao'),
    new FezArtObjectSceneDesc('art_objects/pivot_base_yellowao', 'pivot_base_yellowao'),
    new FezArtObjectSceneDesc('art_objects/pivot_baseao', 'pivot_baseao'),
    new FezArtObjectSceneDesc('art_objects/pivot_ind_caveao', 'pivot_ind_caveao'),
    new FezArtObjectSceneDesc('art_objects/pivot_redao', 'pivot_redao'),
    new FezArtObjectSceneDesc('art_objects/pivot_yellowao', 'pivot_yellowao'),
    new FezArtObjectSceneDesc('art_objects/pivotao', 'pivotao'),
    new FezArtObjectSceneDesc('art_objects/pneumaticao', 'pneumaticao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_banner_aao', 'pyramid_banner_aao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_banner_bao', 'pyramid_banner_bao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_banner_cao', 'pyramid_banner_cao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_banner_torn_aao', 'pyramid_banner_torn_aao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_banner_torn_bao', 'pyramid_banner_torn_bao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_banner_torn_cao', 'pyramid_banner_torn_cao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_statue_owlao', 'pyramid_statue_owlao'),
    new FezArtObjectSceneDesc('art_objects/pyramid_statueao', 'pyramid_statueao'),
    new FezArtObjectSceneDesc('art_objects/qr_cube_foxao', 'qr_cube_foxao'),
    new FezArtObjectSceneDesc('art_objects/rebuilding_hexahedronao', 'rebuilding_hexahedronao'),
    new FezArtObjectSceneDesc('art_objects/reservoirao', 'reservoirao'),
    new FezArtObjectSceneDesc('art_objects/roots_roots_aao', 'roots_roots_aao'),
    new FezArtObjectSceneDesc('art_objects/roots_roots_bao', 'roots_roots_bao'),
    new FezArtObjectSceneDesc('art_objects/rotato_1x1ao', 'rotato_1x1ao'),
    new FezArtObjectSceneDesc('art_objects/rotato_3x3ao', 'rotato_3x3ao'),
    new FezArtObjectSceneDesc('art_objects/rotato_longao', 'rotato_longao'),
    new FezArtObjectSceneDesc('art_objects/save_cube_baseao', 'save_cube_baseao'),
    new FezArtObjectSceneDesc('art_objects/save_cubeao', 'save_cubeao'),
    new FezArtObjectSceneDesc('art_objects/scaffolding_aao', 'scaffolding_aao'),
    new FezArtObjectSceneDesc('art_objects/secret_graveao', 'secret_graveao'),
    new FezArtObjectSceneDesc('art_objects/secret_memoryao', 'secret_memoryao'),
    new FezArtObjectSceneDesc('art_objects/secret_metal_bao', 'secret_metal_bao'),
    new FezArtObjectSceneDesc('art_objects/secret_metal_darkao', 'secret_metal_darkao'),
    new FezArtObjectSceneDesc('art_objects/secret_metalao', 'secret_metalao'),
    new FezArtObjectSceneDesc('art_objects/secret_mineao', 'secret_mineao'),
    new FezArtObjectSceneDesc('art_objects/secret_nuzu_abao', 'secret_nuzu_abao'),
    new FezArtObjectSceneDesc('art_objects/secret_obsao', 'secret_obsao'),
    new FezArtObjectSceneDesc('art_objects/secret_sewer_bao', 'secret_sewer_bao'),
    new FezArtObjectSceneDesc('art_objects/secret_sewerao', 'secret_sewerao'),
    new FezArtObjectSceneDesc('art_objects/secret_throneao', 'secret_throneao'),
    new FezArtObjectSceneDesc('art_objects/secret_treeao', 'secret_treeao'),
    new FezArtObjectSceneDesc('art_objects/secret_visitorao', 'secret_visitorao'),
    new FezArtObjectSceneDesc('art_objects/secret_wallao', 'secret_wallao'),
    new FezArtObjectSceneDesc('art_objects/secret_whiteao', 'secret_whiteao'),
    new FezArtObjectSceneDesc('art_objects/secret_zu_cityao', 'secret_zu_cityao'),
    new FezArtObjectSceneDesc('art_objects/sentinel_wallao', 'sentinel_wallao'),
    new FezArtObjectSceneDesc('art_objects/sewer_bars_aao', 'sewer_bars_aao'),
    new FezArtObjectSceneDesc('art_objects/sewer_big_mouthao', 'sewer_big_mouthao'),
    new FezArtObjectSceneDesc('art_objects/sewer_core_frameao', 'sewer_core_frameao'),
    new FezArtObjectSceneDesc('art_objects/sewer_door_frame_bao', 'sewer_door_frame_bao'),
    new FezArtObjectSceneDesc('art_objects/sewer_doorao', 'sewer_doorao'),
    new FezArtObjectSceneDesc('art_objects/sewer_lava_doorao', 'sewer_lava_doorao'),
    new FezArtObjectSceneDesc('art_objects/sewer_lava_frameao', 'sewer_lava_frameao'),
    new FezArtObjectSceneDesc('art_objects/sewer_lesser_gate_baseao', 'sewer_lesser_gate_baseao'),
    new FezArtObjectSceneDesc('art_objects/sewer_lesser_gateao', 'sewer_lesser_gateao'),
    new FezArtObjectSceneDesc('art_objects/sewer_outao', 'sewer_outao'),
    new FezArtObjectSceneDesc('art_objects/sewer_pivot_baseao', 'sewer_pivot_baseao'),
    new FezArtObjectSceneDesc('art_objects/sewer_pivot_topao', 'sewer_pivot_topao'),
    new FezArtObjectSceneDesc('art_objects/sewer_qr_cube_sonyao', 'sewer_qr_cube_sonyao'),
    new FezArtObjectSceneDesc('art_objects/sewer_qr_cubeao', 'sewer_qr_cubeao'),
    new FezArtObjectSceneDesc('art_objects/sewer_treasure_bottomao', 'sewer_treasure_bottomao'),
    new FezArtObjectSceneDesc('art_objects/sewer_treasure_topao', 'sewer_treasure_topao'),
    new FezArtObjectSceneDesc('art_objects/sewer_valveao', 'sewer_valveao'),
    new FezArtObjectSceneDesc('art_objects/shower_headao', 'shower_headao'),
    new FezArtObjectSceneDesc('art_objects/skull_bao', 'skull_bao'),
    new FezArtObjectSceneDesc('art_objects/skull_jawao', 'skull_jawao'),
    new FezArtObjectSceneDesc('art_objects/skullao', 'skullao'),
    new FezArtObjectSceneDesc('art_objects/skulldoorao', 'skulldoorao'),
    new FezArtObjectSceneDesc('art_objects/spin_red_1x1ao', 'spin_red_1x1ao'),
    new FezArtObjectSceneDesc('art_objects/spin_red_2x1ao', 'spin_red_2x1ao'),
    new FezArtObjectSceneDesc('art_objects/spin_red_2x2_offcenterao', 'spin_red_2x2_offcenterao'),
    new FezArtObjectSceneDesc('art_objects/spin_red_3x11ao', 'spin_red_3x11ao'),
    new FezArtObjectSceneDesc('art_objects/spinblock_aao', 'spinblock_aao'),
    new FezArtObjectSceneDesc('art_objects/spinwall_aao', 'spinwall_aao'),
    new FezArtObjectSceneDesc('art_objects/spiretree_topao', 'spiretree_topao'),
    new FezArtObjectSceneDesc('art_objects/spiretree_trunkao', 'spiretree_trunkao'),
    new FezArtObjectSceneDesc('art_objects/split_up_cubeao', 'split_up_cubeao'),
    new FezArtObjectSceneDesc('art_objects/squid_eye_bigao', 'squid_eye_bigao'),
    new FezArtObjectSceneDesc('art_objects/squid_eye_smallao', 'squid_eye_smallao'),
    new FezArtObjectSceneDesc('art_objects/squid_pillar_aao', 'squid_pillar_aao'),
    new FezArtObjectSceneDesc('art_objects/squid_statue_smallao', 'squid_statue_smallao'),
    new FezArtObjectSceneDesc('art_objects/stargate_aao', 'stargate_aao'),
    new FezArtObjectSceneDesc('art_objects/stargate_bao', 'stargate_bao'),
    new FezArtObjectSceneDesc('art_objects/stargate_pyramid_aao', 'stargate_pyramid_aao'),
    new FezArtObjectSceneDesc('art_objects/stargate_pyramid_bao', 'stargate_pyramid_bao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ring_aao', 'stargate_ring_aao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ring_bao', 'stargate_ring_bao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ring_cao', 'stargate_ring_cao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ring_dao', 'stargate_ring_dao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ruin_aao', 'stargate_ruin_aao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ruin_bao', 'stargate_ruin_bao'),
    new FezArtObjectSceneDesc('art_objects/stargate_ruin_cao', 'stargate_ruin_cao'),
    new FezArtObjectSceneDesc('art_objects/stargate_sao', 'stargate_sao'),
    new FezArtObjectSceneDesc('art_objects/stone_door_frameao', 'stone_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/student_deskao', 'student_deskao'),
    new FezArtObjectSceneDesc('art_objects/tall_tree_aao', 'tall_tree_aao'),
    new FezArtObjectSceneDesc('art_objects/teacher_desk_nuzuao', 'teacher_desk_nuzuao'),
    new FezArtObjectSceneDesc('art_objects/teacher_deskao', 'teacher_deskao'),
    new FezArtObjectSceneDesc('art_objects/telescope_lenseao', 'telescope_lenseao'),
    new FezArtObjectSceneDesc('art_objects/telescope_seatao', 'telescope_seatao'),
    new FezArtObjectSceneDesc('art_objects/telescopeao', 'telescopeao'),
    new FezArtObjectSceneDesc('art_objects/tetris_entranceao', 'tetris_entranceao'),
    new FezArtObjectSceneDesc('art_objects/tetris_puzzle_baseao', 'tetris_puzzle_baseao'),
    new FezArtObjectSceneDesc('art_objects/throne_aao', 'throne_aao'),
    new FezArtObjectSceneDesc('art_objects/throne_bao', 'throne_bao'),
    new FezArtObjectSceneDesc('art_objects/throne_thingao', 'throne_thingao'),
    new FezArtObjectSceneDesc('art_objects/timeswitch_baseao', 'timeswitch_baseao'),
    new FezArtObjectSceneDesc('art_objects/timeswitch_coreao', 'timeswitch_coreao'),
    new FezArtObjectSceneDesc('art_objects/timeswitch_postao', 'timeswitch_postao'),
    new FezArtObjectSceneDesc('art_objects/tiny_chapeauao', 'tiny_chapeauao'),
    new FezArtObjectSceneDesc('art_objects/tombstoneao', 'tombstoneao'),
    new FezArtObjectSceneDesc('art_objects/tome_bao', 'tome_bao'),
    new FezArtObjectSceneDesc('art_objects/tome_coverao', 'tome_coverao'),
    new FezArtObjectSceneDesc('art_objects/tomeao', 'tomeao'),
    new FezArtObjectSceneDesc('art_objects/totem_bao', 'totem_bao'),
    new FezArtObjectSceneDesc('art_objects/totemao', 'totemao'),
    new FezArtObjectSceneDesc('art_objects/towerblockao', 'towerblockao'),
    new FezArtObjectSceneDesc('art_objects/tracks0ao', 'tracks0ao'),
    new FezArtObjectSceneDesc('art_objects/tracks1ao', 'tracks1ao'),
    new FezArtObjectSceneDesc('art_objects/tracks2ao', 'tracks2ao'),
    new FezArtObjectSceneDesc('art_objects/trappedao', 'trappedao'),
    new FezArtObjectSceneDesc('art_objects/trashcan_lidao', 'trashcan_lidao'),
    new FezArtObjectSceneDesc('art_objects/trashcan_sideao', 'trashcan_sideao'),
    new FezArtObjectSceneDesc('art_objects/trashcanao', 'trashcanao'),
    new FezArtObjectSceneDesc('art_objects/treasure_mapao', 'treasure_mapao'),
    new FezArtObjectSceneDesc('art_objects/treasure_virtual_bottomao', 'treasure_virtual_bottomao'),
    new FezArtObjectSceneDesc('art_objects/treasure_virtual_topao', 'treasure_virtual_topao'),
    new FezArtObjectSceneDesc('art_objects/treasureao', 'treasureao'),
    new FezArtObjectSceneDesc('art_objects/treasurebottomao', 'treasurebottomao'),
    new FezArtObjectSceneDesc('art_objects/treasuretopao', 'treasuretopao'),
    new FezArtObjectSceneDesc('art_objects/tree_of_deathao', 'tree_of_deathao'),
    new FezArtObjectSceneDesc('art_objects/tri_skullao', 'tri_skullao'),
    new FezArtObjectSceneDesc('art_objects/up_signao', 'up_signao'),
    new FezArtObjectSceneDesc('art_objects/village_big_crateao', 'village_big_crateao'),
    new FezArtObjectSceneDesc('art_objects/village_tankao', 'village_tankao'),
    new FezArtObjectSceneDesc('art_objects/visitor_aao', 'visitor_aao'),
    new FezArtObjectSceneDesc('art_objects/visitor_bao', 'visitor_bao'),
    new FezArtObjectSceneDesc('art_objects/visitor_cao', 'visitor_cao'),
    new FezArtObjectSceneDesc('art_objects/visitor_dao', 'visitor_dao'),
    new FezArtObjectSceneDesc('art_objects/wall_entranceao', 'wall_entranceao'),
    new FezArtObjectSceneDesc('art_objects/walldoor_aao', 'walldoor_aao'),
    new FezArtObjectSceneDesc('art_objects/walldoor_bao', 'walldoor_bao'),
    new FezArtObjectSceneDesc('art_objects/wallwindow_aao', 'wallwindow_aao'),
    new FezArtObjectSceneDesc('art_objects/wallwindow_bao', 'wallwindow_bao'),
    new FezArtObjectSceneDesc('art_objects/wallwindow_cao', 'wallwindow_cao'),
    new FezArtObjectSceneDesc('art_objects/warning_signao', 'warning_signao'),
    new FezArtObjectSceneDesc('art_objects/warproom_postaao', 'warproom_postaao'),
    new FezArtObjectSceneDesc('art_objects/water_doorframe_bao', 'water_doorframe_bao'),
    new FezArtObjectSceneDesc('art_objects/water_doorframeao', 'water_doorframeao'),
    new FezArtObjectSceneDesc('art_objects/water_statue_baseao', 'water_statue_baseao'),
    new FezArtObjectSceneDesc('art_objects/water_statueao', 'water_statueao'),
    new FezArtObjectSceneDesc('art_objects/water_tower_legsao', 'water_tower_legsao'),
    new FezArtObjectSceneDesc('art_objects/water_towerao', 'water_towerao'),
    new FezArtObjectSceneDesc('art_objects/water_valve_podiumao', 'water_valve_podiumao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_head_eye_aao', 'waterfall_head_eye_aao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_head_eye_bao', 'waterfall_head_eye_bao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_head_mouthao', 'waterfall_head_mouthao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_headao', 'waterfall_headao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_support_aao', 'waterfall_support_aao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_support_bao', 'waterfall_support_bao'),
    new FezArtObjectSceneDesc('art_objects/waterfall_support_cao', 'waterfall_support_cao'),
    new FezArtObjectSceneDesc('art_objects/watertower_owl_body_ao', 'watertower_owl_body_ao'),
    new FezArtObjectSceneDesc('art_objects/watertower_owl_bodyao', 'watertower_owl_bodyao'),
    new FezArtObjectSceneDesc('art_objects/watertower_owl_head_ao', 'watertower_owl_head_ao'),
    new FezArtObjectSceneDesc('art_objects/watertower_owl_headao', 'watertower_owl_headao'),
    new FezArtObjectSceneDesc('art_objects/waterwheel_baseao', 'waterwheel_baseao'),
    new FezArtObjectSceneDesc('art_objects/waterwheelao', 'waterwheelao'),
    new FezArtObjectSceneDesc('art_objects/weight_switch_baseao', 'weight_switch_baseao'),
    new FezArtObjectSceneDesc('art_objects/wellao', 'wellao'),
    new FezArtObjectSceneDesc('art_objects/white_watermouthao', 'white_watermouthao'),
    new FezArtObjectSceneDesc('art_objects/windmill_bao', 'windmill_bao'),
    new FezArtObjectSceneDesc('art_objects/windmill_core_aao', 'windmill_core_aao'),
    new FezArtObjectSceneDesc('art_objects/windmill_core_bao', 'windmill_core_bao'),
    new FezArtObjectSceneDesc('art_objects/windmill_core_cao', 'windmill_core_cao'),
    new FezArtObjectSceneDesc('art_objects/windmill_int_aao', 'windmill_int_aao'),
    new FezArtObjectSceneDesc('art_objects/windmill_int_bao', 'windmill_int_bao'),
    new FezArtObjectSceneDesc('art_objects/windmill_int_cao', 'windmill_int_cao'),
    new FezArtObjectSceneDesc('art_objects/windmill_int_dao', 'windmill_int_dao'),
    new FezArtObjectSceneDesc('art_objects/windmillao', 'windmillao'),
    new FezArtObjectSceneDesc('art_objects/wooden_door_frameao', 'wooden_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/woodhouse_aao', 'woodhouse_aao'),
    new FezArtObjectSceneDesc('art_objects/yu_statue_aao', 'yu_statue_aao'),
    new FezArtObjectSceneDesc('art_objects/yu_statue_bao', 'yu_statue_bao'),
    new FezArtObjectSceneDesc('art_objects/zu_bazaar_0ao', 'zu_bazaar_0ao'),
    new FezArtObjectSceneDesc('art_objects/zu_bazaar_1ao', 'zu_bazaar_1ao'),
    new FezArtObjectSceneDesc('art_objects/zu_bazaar_2ao', 'zu_bazaar_2ao'),
    new FezArtObjectSceneDesc('art_objects/zu_bazaar_3ao', 'zu_bazaar_3ao'),
    new FezArtObjectSceneDesc('art_objects/zu_bustao', 'zu_bustao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_big_doorframeao', 'zu_city_big_doorframeao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_door_pao', 'zu_city_door_pao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_doorao', 'zu_city_doorao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_waterfaceao', 'zu_city_waterfaceao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_watermouthao', 'zu_city_watermouthao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_window_pao', 'zu_city_window_pao'),
    new FezArtObjectSceneDesc('art_objects/zu_city_windowao', 'zu_city_windowao'),
    new FezArtObjectSceneDesc('art_objects/zu_door_frameao', 'zu_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/zu_doorao', 'zu_doorao'),
    new FezArtObjectSceneDesc('art_objects/zu_gateao', 'zu_gateao'),
    new FezArtObjectSceneDesc('art_objects/zu_house_doorao', 'zu_house_doorao'),
    new FezArtObjectSceneDesc('art_objects/zu_kiosk_aao', 'zu_kiosk_aao'),
    new FezArtObjectSceneDesc('art_objects/zu_kiosk_bao', 'zu_kiosk_bao'),
    new FezArtObjectSceneDesc('art_objects/zu_kiosk_cao', 'zu_kiosk_cao'),
    new FezArtObjectSceneDesc('art_objects/zu_lao', 'zu_lao'),
    new FezArtObjectSceneDesc('art_objects/zu_secret_entranceao', 'zu_secret_entranceao'),
    new FezArtObjectSceneDesc('art_objects/zu_signao', 'zu_signao'),
    new FezArtObjectSceneDesc('art_objects/zu_stone_door_frameao', 'zu_stone_door_frameao'),
    new FezArtObjectSceneDesc('art_objects/zu_tao', 'zu_tao'),
    new FezArtObjectSceneDesc('art_objects/zu_window_barsao', 'zu_window_barsao'),
    new FezArtObjectSceneDesc('art_objects/zu_zao', 'zu_zao'),
    new FezArtObjectSceneDesc('art_objects/zuhead_a_w_gao', 'zuhead_a_w_gao'),
    new FezArtObjectSceneDesc('art_objects/zuhead_a_wao', 'zuhead_a_wao'),
    new FezArtObjectSceneDesc('art_objects/zuhead_aao', 'zuhead_aao'),
    new FezArtObjectSceneDesc('art_objects/zuhead_b_w_gao', 'zuhead_b_w_gao'),
    new FezArtObjectSceneDesc('art_objects/zuhead_b_wao', 'zuhead_b_wao'),
    new FezArtObjectSceneDesc('art_objects/zuhead_bao', 'zuhead_bao'),
    new FezArtObjectSceneDesc('art_objects/zuish_monolith_aao', 'zuish_monolith_aao'),
    new FezArtObjectSceneDesc('art_objects/zuon_bodyao', 'zuon_bodyao'),
    new FezArtObjectSceneDesc('art_objects/zuon_eyeao', 'zuon_eyeao'),
    new FezArtObjectSceneDesc('art_objects/zuon_headao', 'zuon_headao'),
    new FezArtObjectSceneDesc('art_objects/zuon_legsao', 'zuon_legsao'),
];

const sceneIdMap = new Map<string, string>([
    ['abandoned_a', 'levels/abandoned_a'],
    ['abandoned_b', 'levels/abandoned_b'],
    ['abandoned_c', 'levels/abandoned_c'],
    ['ancient_walls', 'levels/ancient_walls'],
    ['arch', 'levels/arch'],
    ['bell_tower', 'levels/bell_tower'],
    ['big_owl', 'levels/big_owl'],
    ['big_tower', 'levels/big_tower'],
    ['boileroom', 'levels/boileroom'],
    ['cabin_interior_a', 'levels/cabin_interior_a'],
    ['cabin_interior_b', 'levels/cabin_interior_b'],
    ['clock', 'levels/clock'],
    ['cmy', 'levels/cmy'],
    ['cmy_b', 'levels/cmy_b'],
    ['cmy_fork', 'levels/cmy_fork'],
    ['code_machine', 'levels/code_machine'],
    ['crypt', 'levels/crypt'],
    ['drum', 'levels/drum'],
    ['elders', 'levels/elders'],
    ['extractor_a', 'levels/extractor_a'],
    ['five_towers', 'levels/five_towers'],
    ['five_towers_cave', 'levels/five_towers_cave'],
    ['fox', 'levels/fox'],
    ['fractal', 'levels/fractal'],
    ['geezer_house', 'levels/geezer_house'],
    ['geezer_house_2d', 'levels/geezer_house_2d'],
    ['globe', 'levels/globe'],
    ['globe_int', 'levels/globe_int'],
    ['gomez_house', 'levels/gomez_house'],
    ['gomez_house_2d', 'levels/gomez_house_2d'],
    ['gomez_house_end_32', 'levels/gomez_house_end_32'],
    ['gomez_house_end_64', 'levels/gomez_house_end_64'],
    ['grave_cabin', 'levels/grave_cabin'],
    ['grave_ghost', 'levels/grave_ghost'],
    ['grave_lesser_gate', 'levels/grave_lesser_gate'],
    ['grave_treasure_a', 'levels/grave_treasure_a'],
    ['graveyard_a', 'levels/graveyard_a'],
    ['graveyard_gate', 'levels/graveyard_gate'],
    ['hex_rebuild', 'levels/hex_rebuild'],
    ['indust_abandoned_a', 'levels/indust_abandoned_a'],
    ['industrial_city', 'levels/industrial_city'],
    ['industrial_hub', 'levels/industrial_hub'],
    ['industrial_superspin', 'levels/industrial_superspin'],
    ['kitchen', 'levels/kitchen'],
    ['kitchen_2d', 'levels/kitchen_2d'],
    ['lava', 'levels/lava'],
    ['lava_fork', 'levels/lava_fork'],
    ['lava_skull', 'levels/lava_skull'],
    ['library_interior', 'levels/library_interior'],
    ['lighthouse', 'levels/lighthouse'],
    ['lighthouse_house_a', 'levels/lighthouse_house_a'],
    ['lighthouse_spin', 'levels/lighthouse_spin'],
    ['mausoleum', 'levels/mausoleum'],
    ['memory_core', 'levels/memory_core'],
    ['mine_a', 'levels/mine_a'],
    ['mine_bomb_pillar', 'levels/mine_bomb_pillar'],
    ['mine_wrap', 'levels/mine_wrap'],
    ['nature_hub', 'levels/nature_hub'],
    ['nuzu_abandoned_a', 'levels/nuzu_abandoned_a'],
    ['nuzu_abandoned_b', 'levels/nuzu_abandoned_b'],
    ['nuzu_boilerroom', 'levels/nuzu_boilerroom'],
    ['nuzu_dorm', 'levels/nuzu_dorm'],
    ['nuzu_school', 'levels/nuzu_school'],
    ['observatory', 'levels/observatory'],
    ['octoheahedron', 'levels/octoheahedron'],
    ['oldschool', 'levels/oldschool'],
    ['oldschool_ruins', 'levels/oldschool_ruins'],
    ['orrery', 'levels/orrery'],
    ['orrery_b', 'levels/orrery_b'],
    ['owl', 'levels/owl'],
    ['parlor', 'levels/parlor'],
    ['parlor_2d', 'levels/parlor_2d'],
    ['pivot_one', 'levels/pivot_one'],
    ['pivot_two', 'levels/pivot_two'],
    ['pivot_three', 'levels/pivot_three'],
    ['pivot_three_cave', 'levels/pivot_three_cave'],
    ['pivot_watertower', 'levels/pivot_watertower'],
    ['purple_lodge', 'levels/purple_lodge'],
    ['purple_lodge_ruin', 'levels/purple_lodge_ruin'],
    ['pyramid', 'levels/pyramid'],
    ['quantum', 'levels/quantum'],
    ['rails', 'levels/rails'],
    ['ritual', 'levels/ritual'],
    ['school', 'levels/school'],
    ['school_2d', 'levels/school_2d'],
    ['sewer_fork', 'levels/sewer_fork'],
    ['sewer_geyser', 'levels/sewer_geyser'],
    ['sewer_hub', 'levels/sewer_hub'],
    ['sewer_lesser_gate_b', 'levels/sewer_lesser_gate_b'],
    ['sewer_pillars', 'levels/sewer_pillars'],
    ['sewer_pivot', 'levels/sewer_pivot'],
    ['sewer_qr', 'levels/sewer_qr'],
    ['sewer_start', 'levels/sewer_start'],
    ['sewer_to_lava', 'levels/sewer_to_lava'],
    ['sewer_treasure_one', 'levels/sewer_treasure_one'],
    ['sewer_treasure_two', 'levels/sewer_treasure_two'],
    ['showers', 'levels/showers'],
    ['skull', 'levels/skull'],
    ['skull_b', 'levels/skull_b'],
    ['spinning_plates', 'levels/spinning_plates'],
    ['stargate', 'levels/stargate'],
    ['stargate_ruins', 'levels/stargate_ruins'],
    ['superspin_cave', 'levels/superspin_cave'],
    ['telescope', 'levels/telescope'],
    ['temple_of_love', 'levels/temple_of_love'],
    ['throne', 'levels/throne'],
    ['tree', 'levels/tree'],
    ['tree_crumble', 'levels/tree_crumble'],
    ['tree_of_death', 'levels/tree_of_death'],
    ['tree_roots', 'levels/tree_roots'],
    ['tree_sky', 'levels/tree_sky'],
    ['triple_pivot_cave', 'levels/triple_pivot_cave'],
    ['two_walls', 'levels/two_walls'],
    ['villageville_2d', 'levels/villageville_2d'],
    ['villageville_3d', 'levels/villageville_3d'],
    ['villageville_3d_end_32', 'levels/villageville_3d_end_32'],
    ['villageville_3d_end_64', 'levels/villageville_3d_end_64'],
    ['visitor', 'levels/visitor'],
    ['wall_hole', 'levels/wall_hole'],
    ['wall_interior_a', 'levels/wall_interior_a'],
    ['wall_interior_b', 'levels/wall_interior_b'],
    ['wall_interior_hole', 'levels/wall_interior_hole'],
    ['wall_kitchen', 'levels/wall_kitchen'],
    ['wall_school', 'levels/wall_school'],
    ['wall_village', 'levels/wall_village'],
    ['water_pyramid', 'levels/water_pyramid'],
    ['water_tower', 'levels/water_tower'],
    ['water_wheel', 'levels/water_wheel'],
    ['water_wheel_b', 'levels/water_wheel_b'],
    ['waterfall', 'levels/waterfall'],
    ['waterfall_alt', 'levels/waterfall_alt'],
    ['watertower_secret', 'levels/watertower_secret'],
    ['weightswitch_temple', 'levels/weightswitch_temple'],
    ['well_2', 'levels/well_2'],
    ['windmill_cave', 'levels/windmill_cave'],
    ['windmill_int', 'levels/windmill_int'],
    ['zu_4_side', 'levels/zu_4_side'],
    ['zu_bridge', 'levels/zu_bridge'],
    ['zu_city', 'levels/zu_city'],
    ['zu_city_ruins', 'levels/zu_city_ruins'],
    ['zu_code_loop', 'levels/zu_code_loop'],
    ['zu_fork', 'levels/zu_fork'],
    ['zu_heads', 'levels/zu_heads'],
    ['zu_house_empty', 'levels/zu_house_empty'],
    ['zu_house_empty_b', 'levels/zu_house_empty_b'],
    ['zu_house_qr', 'levels/zu_house_qr'],
    ['zu_house_ruin_gate', 'levels/zu_house_ruin_gate'],
    ['zu_house_ruin_visitors', 'levels/zu_house_ruin_visitors'],
    ['zu_house_scaffolding', 'levels/zu_house_scaffolding'],
    ['zu_library', 'levels/zu_library'],
    ['zu_switch', 'levels/zu_switch'],
    ['zu_switch_b', 'levels/zu_switch_b'],
    ['zu_tetris', 'levels/zu_tetris'],
    ['zu_throne_ruins', 'levels/zu_throne_ruins'],
    ['zu_unfold', 'levels/zu_unfold'],
    ['zu_zuish', 'levels/zu_zuish'],
]);

export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs, sceneIdMap };
